import BodyFinderNative from '../modules/body-finder-native';
import { Advertisement } from './autogeometry';

export type AuthorityCohortMember={node_id:string;instance_epoch:string};
export type AuthorityViewV1={schema:'AuthorityViewV1';session_id:string;cohort:AuthorityCohortMember[];elected_coordinator:string;coordinator_generation:number;base_digest:string;authority_view_digest:string};
export type AuthorityAckV1={schema:'AuthorityAckV1';session_id:string;node_id:string;authority_view_digest:string;coordinator_generation:number};
type State={baseDigest:string|null;generation:number;pinned:boolean;pinnedView:AuthorityViewV1|null};
const states=new Map<string,State>();
function canonical(v:any):string{if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return'['+v.map(canonical).join(',')+']';return'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}'}
function sha(v:unknown){return BodyFinderNative.sha256Text(typeof v==='string'?v:canonical(v))}
function currentSession(nodes:Advertisement[]){const c=new Map<string,number>();for(const n of nodes){if(n.protocol_version===2&&n.session_id)c.set(String(n.session_id),(c.get(String(n.session_id))??0)+1)}return[...c.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))[0]?.[0]??'body-finder-lab'}
function live(nodes:Advertisement[],sid:string){return nodes.filter(n=>n.protocol_version===2&&String(n.session_id)===sid&&Boolean(n.node_id)&&Number((n as any).membership_lease_age_ms??0)<=15_000&&String((n as any).membership_lease_state??'LIVE')!=='EXPIRED')}
function completeCohort(nodes:Advertisement[],sid:string){const by=new Map<string,Advertisement>();for(const n of live(nodes,sid)){const id=String(n.node_id);const prior=by.get(id);if(!prior||Number((n as any).membership_lease_age_ms??0)<=Number((prior as any).membership_lease_age_ms??0))by.set(id,n)}if(by.size!==3)return null;return[...by.values()].sort((a,b)=>String(a.node_id).localeCompare(String(b.node_id)))}
function state(sid:string){let s=states.get(sid);if(!s){s={baseDigest:null,generation:0,pinned:false,pinnedView:null};states.set(sid,s)}return s}
function peerViews(nodes:Advertisement[]){return nodes.map(n=>(n.control_plane as any)?.authority_view_v1 as AuthorityViewV1|undefined).filter((v):v is AuthorityViewV1=>Boolean(v&&v.schema==='AuthorityViewV1'))}
function compute(nodes:Advertisement[]):AuthorityViewV1|null{const sid=currentSession(nodes),s=state(sid);if(s.pinned&&s.pinnedView)return s.pinnedView;const cohortNodes=completeCohort(nodes,sid);if(!cohortNodes)return null;const cohort=cohortNodes.map(n=>({node_id:String(n.node_id),instance_epoch:String((n as any).instance_epoch??'legacy')}));const elected=[...cohortNodes].sort((a,b)=>Number(b.coordinator_score??0)-Number(a.coordinator_score??0)||String(a.node_id).localeCompare(String(b.node_id)))[0]?.node_id;if(!elected)return null;const base={session_id:sid,cohort,elected_coordinator:String(elected)},baseDigest=sha(base),views=peerViews(nodes);if(s.baseDigest!==baseDigest){const maxObserved=Math.max(0,...views.map(v=>Number(v.coordinator_generation??0)));s.generation=Math.max(1,s.generation+1,maxObserved+1);s.baseDigest=baseDigest}else{const same=views.filter(v=>v.base_digest===baseDigest);s.generation=Math.max(s.generation,1,...same.map(v=>Number(v.coordinator_generation??0)))}const material={...base,coordinator_generation:s.generation},view:AuthorityViewV1={schema:'AuthorityViewV1',...material,base_digest:baseDigest,authority_view_digest:sha(material)};const committed=nodes.some(n=>{const c=(n.control_plane as any)?.run_start_commit_v1;return c?.schema==='RunStartCommitV1'&&c?.authority_view_digest===view.authority_view_digest});if(committed){s.pinned=true;s.pinnedView=view}return view}
export function getAuthorityStatus(nodes:Advertisement[],localNodeId:string|null){const view=compute(nodes);if(!view)return{schema:'AuthorityStatusV1',view:null,ack_matrix:[],ack_count:0,consensus:false,blocking_reasons:['AUTHORITY_COHORT_INCOMPLETE']};const ids=view.cohort.map(x=>x.node_id);const ack_matrix=ids.map(id=>{if(id===localNodeId)return{node_id:id,acknowledged:true,authority_view_digest:view.authority_view_digest};const cp=(nodes.find(n=>n.node_id===id)?.control_plane as any);const pv=cp?.authority_view_v1,pa=cp?.authority_ack_v1;const ok=pv?.schema==='AuthorityViewV1'&&pv?.authority_view_digest===view.authority_view_digest&&pa?.schema==='AuthorityAckV1'&&pa?.node_id===id&&pa?.authority_view_digest===view.authority_view_digest&&Number(pa?.coordinator_generation)===view.coordinator_generation;return{node_id:id,acknowledged:Boolean(ok),authority_view_digest:pa?.authority_view_digest??null}});const ack_count=ack_matrix.filter(x=>x.acknowledged).length,consensus=ids.length===3&&ack_count===3;return{schema:'AuthorityStatusV1',view,ack_matrix,ack_count,consensus,blocking_reasons:consensus?[]:['AUTHORITY_ACK_3_OF_3_REQUIRED']}}
export function getAuthorityControlPublication(nodes:Advertisement[],localNodeId:string|null){const status=getAuthorityStatus(nodes,localNodeId),view=status.view;const ack=view&&localNodeId&&view.cohort.some(x=>x.node_id===localNodeId)?{schema:'AuthorityAckV1',session_id:view.session_id,node_id:localNodeId,authority_view_digest:view.authority_view_digest,coordinator_generation:view.coordinator_generation}:null;return{authority_view_v1:view,authority_ack_v1:ack}}
export function deterministicCoordinator(nodes:Advertisement[],localNodeId:string|null){return getAuthorityStatus(nodes,localNodeId).view?.elected_coordinator??null}
