import BodyFinderNative from '../modules/body-finder-native';
import { Advertisement } from './autogeometry';

export type AuthorityCohortMember={node_id:string;instance_epoch:string};
export type AuthorityViewV1={schema:'AuthorityViewV1';session_id:string;cohort:AuthorityCohortMember[];elected_coordinator:string;coordinator_generation:number;base_digest:string;authority_view_digest:string};
export type AuthorityWireV2={schema:'AuthorityWireV2';s:string;e:string;g:number;b:string;d:string};
export type AuthorityAckWireV2={schema:'AuthorityAckWireV2';s:string;n:string;e:string;g:number;b:string;d:string};
type PeerCommitment={schema:'AuthorityWireV2'|'AuthorityViewV1';session_id:string;elected_coordinator:string;coordinator_generation:number;base_digest:string;authority_view_digest:string};
type State={baseDigest:string|null;generation:number;pinned:boolean;pinnedView:AuthorityViewV1|null};
const states=new Map<string,State>();
type AuthorityConvergenceEvent={wall_ms:number;generation:number;ack_count:number;consensus:boolean;base_digest:string;authority_view_digest:string};
const convergenceBySession=new Map<string,AuthorityConvergenceEvent[]>();
function noteConvergence(sid:string,view:AuthorityViewV1,ackCount:number,consensus:boolean){const prior=convergenceBySession.get(sid)??[],last=prior.at(-1);if(!last||last.generation!==view.coordinator_generation||last.ack_count!==ackCount||last.authority_view_digest!==view.authority_view_digest||last.consensus!==consensus){prior.push({wall_ms:Date.now(),generation:view.coordinator_generation,ack_count:ackCount,consensus,base_digest:view.base_digest,authority_view_digest:view.authority_view_digest});convergenceBySession.set(sid,prior.slice(-64))}}
function canonical(v:any):string{if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return'['+v.map(canonical).join(',')+']';return'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}'}
function sha(v:unknown){return BodyFinderNative.sha256Text(typeof v==='string'?v:canonical(v))}
function currentSession(nodes:Advertisement[]){const c=new Map<string,number>();for(const n of nodes){if(n.protocol_version===2&&n.session_id)c.set(String(n.session_id),(c.get(String(n.session_id))??0)+1)}return[...c.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))[0]?.[0]??'body-finder-lab'}
function live(nodes:Advertisement[],sid:string){return nodes.filter(n=>n.protocol_version===2&&String(n.session_id)===sid&&Boolean(n.node_id)&&Number((n as any).membership_lease_age_ms??0)<=15_000&&String((n as any).membership_lease_state??'LIVE')!=='EXPIRED')}
function epochOf(n:Advertisement){const e=String((n as any).instance_epoch??'').trim();return e&&e!=='legacy'?e:null}
function completeCohort(nodes:Advertisement[],sid:string){const by=new Map<string,Advertisement[]>();for(const n of live(nodes,sid)){const id=String(n.node_id),epoch=epochOf(n);if(!epoch)continue;by.set(id,[...(by.get(id)??[]),n])}if(by.size!==3)return null;const selected=[...by.entries()].map(([,items])=>items.sort((a,b)=>Number((a as any).membership_lease_age_ms??0)-Number((b as any).membership_lease_age_ms??0)||String(epochOf(a)).localeCompare(String(epochOf(b))))[0]);return selected.sort((a,b)=>String(a.node_id).localeCompare(String(b.node_id))||String(epochOf(a)).localeCompare(String(epochOf(b))))}
function state(sid:string){let s=states.get(sid);if(!s){s={baseDigest:null,generation:0,pinned:false,pinnedView:null};states.set(sid,s)}return s}
function commitment(v:any):PeerCommitment|undefined{if(v?.schema==='AuthorityWireV2'&&typeof v.s==='string'&&typeof v.e==='string'&&Number.isFinite(Number(v.g))&&typeof v.b==='string'&&typeof v.d==='string')return{schema:'AuthorityWireV2',session_id:v.s,elected_coordinator:v.e,coordinator_generation:Number(v.g),base_digest:v.b,authority_view_digest:v.d};if(v?.schema==='AuthorityViewV1'&&typeof v.session_id==='string'&&typeof v.elected_coordinator==='string'&&Number.isFinite(Number(v.coordinator_generation))&&typeof v.base_digest==='string'&&typeof v.authority_view_digest==='string')return{schema:'AuthorityViewV1',session_id:v.session_id,elected_coordinator:v.elected_coordinator,coordinator_generation:Number(v.coordinator_generation),base_digest:v.base_digest,authority_view_digest:v.authority_view_digest};return undefined}
function peerCommitments(nodes:Advertisement[]){return nodes.map(n=>commitment((n.control_plane as any)?.authority_view_v1)).filter((v):v is PeerCommitment=>Boolean(v))}
function encodeView(v:AuthorityViewV1):AuthorityWireV2{return{schema:'AuthorityWireV2',s:v.session_id,e:v.elected_coordinator,g:v.coordinator_generation,b:v.base_digest,d:v.authority_view_digest}}
function compute(nodes:Advertisement[]):AuthorityViewV1|null{const sid=currentSession(nodes),s=state(sid);if(s.pinned&&s.pinnedView)return s.pinnedView;const cohortNodes=completeCohort(nodes,sid);if(!cohortNodes)return null;const cohort=cohortNodes.map(n=>({node_id:String(n.node_id),instance_epoch:epochOf(n)!}));const elected=[...cohortNodes].sort((a,b)=>Number(b.coordinator_score??0)-Number(a.coordinator_score??0)||String(a.node_id).localeCompare(String(b.node_id))||String(epochOf(a)).localeCompare(String(epochOf(b))))[0]?.node_id;if(!elected)return null;const base={session_id:sid,cohort,elected_coordinator:String(elected)},baseDigest=sha(base),views=peerCommitments(nodes).filter(v=>v.session_id===sid),same=views.filter(v=>v.base_digest===baseDigest&&v.elected_coordinator===String(elected));if(s.baseDigest!==baseDigest){if(same.length){s.generation=Math.max(1,...same.map(v=>v.coordinator_generation))}else{const maxObserved=Math.max(s.generation,0,...views.map(v=>v.coordinator_generation));s.generation=(s.baseDigest!==null||views.length>0)?Math.max(1,maxObserved+1):1}s.baseDigest=baseDigest}else{s.generation=Math.max(s.generation,1,...same.map(v=>v.coordinator_generation))}const material={...base,coordinator_generation:s.generation},view:AuthorityViewV1={schema:'AuthorityViewV1',...material,base_digest:baseDigest,authority_view_digest:sha(material)};const committed=nodes.some(n=>{const c=(n.control_plane as any)?.run_start_commit_v1;return c?.schema==='RunStartCommitV1'&&c?.authority_view_digest===view.authority_view_digest});if(committed){s.pinned=true;s.pinnedView=view}return view}
function epochBlocker(nodes:Advertisement[],sid:string){const current=live(nodes,sid),ids=[...new Set(current.map(n=>String(n.node_id)))];return ids.length===3&&current.some(n=>!epochOf(n))}
export function getAuthorityStatus(nodes:Advertisement[],localNodeId:string|null){const sid=currentSession(nodes),view=compute(nodes);if(!view)return{schema:'AuthorityStatusV2',view:null,canonical_cohort_input:[],ack_matrix:[],ack_count:0,consensus:false,blocking_reasons:[epochBlocker(nodes,sid)?'AUTHORITY_INSTANCE_EPOCH_UNINITIALIZED':'AUTHORITY_COHORT_INCOMPLETE']};const ids=view.cohort.map(x=>x.node_id);const ack_matrix=ids.map(id=>{if(id===localNodeId)return{node_id:id,acknowledged:true,authority_view_digest:view.authority_view_digest};const cp=(nodes.find(n=>n.node_id===id)?.control_plane as any),rawView=cp?.authority_view_v1,pv=commitment(rawView),pa=cp?.authority_ack_v1;const viewOk=rawView?.schema==='AuthorityWireV2'&&pv?.session_id===view.session_id&&pv?.elected_coordinator===view.elected_coordinator&&pv?.coordinator_generation===view.coordinator_generation&&pv?.base_digest===view.base_digest&&pv?.authority_view_digest===view.authority_view_digest;const ackOk=pa?.schema==='AuthorityAckWireV2'&&pa?.s===view.session_id&&pa?.n===id&&pa?.e===view.elected_coordinator&&Number(pa?.g)===view.coordinator_generation&&pa?.b===view.base_digest&&pa?.d===view.authority_view_digest;return{node_id:id,acknowledged:Boolean(viewOk&&ackOk),authority_view_digest:pa?.d??pa?.authority_view_digest??null}});const ack_count=ack_matrix.filter(x=>x.acknowledged).length,consensus=ids.length===3&&ack_count===3,rejected_ack_count=ids.filter(id=>id!==localNodeId).filter(id=>{const cp=(nodes.find(n=>n.node_id===id)?.control_plane as any);return Boolean(cp?.authority_ack_v1)&&!ack_matrix.find(x=>x.node_id===id)?.acknowledged}).length;noteConvergence(sid,view,ack_count,consensus);const convergence_timeline=convergenceBySession.get(sid)??[];return{schema:'AuthorityStatusV2',view,canonical_cohort_input:view.cohort,base_digest:view.base_digest,authority_view_digest:view.authority_view_digest,coordinator_generation:view.coordinator_generation,authority_generation_history:convergence_timeline.map(x=>({wall_ms:x.wall_ms,generation:x.generation,base_digest:x.base_digest,authority_view_digest:x.authority_view_digest})),convergence_timeline,stale_or_foreign_ack_rejection_count:rejected_ack_count,ack_matrix,ack_count,consensus,blocking_reasons:consensus?[]:['AUTHORITY_ACK_3_OF_3_REQUIRED']}}
export function getAuthorityControlPublication(nodes:Advertisement[],localNodeId:string|null){const status=getAuthorityStatus(nodes,localNodeId),view=status.view;const ack:AuthorityAckWireV2|null=view&&localNodeId&&view.cohort.some(x=>x.node_id===localNodeId)?{schema:'AuthorityAckWireV2',s:view.session_id,n:localNodeId,e:view.elected_coordinator,g:view.coordinator_generation,b:view.base_digest,d:view.authority_view_digest}:null;return{authority_view_v1:view?encodeView(view):null,authority_ack_v1:ack}}
export function deterministicCoordinator(nodes:Advertisement[],localNodeId:string|null){return getAuthorityStatus(nodes,localNodeId).view?.elected_coordinator??null}
