import BodyFinderNative from '../modules/body-finder-native';
import { Advertisement } from './autogeometry';

export type ScenarioId = 'SMOKE_CAL_EMPTY'|'HUMAN_MOVING'|'EMPTY_CAL'|'EMPTY_TEST'|'HUMAN_STATIONARY_CENTER'|'HUMAN_NEAR_LENOVO'|'HUMAN_NEAR_PIXEL10'|'HUMAN_NEAR_PIXEL7'|'HUMAN_OUTSIDE'|'NON_HUMAN_MOTION';
export type ScenarioCommandV1 = {schema:'ScenarioCommandV1';campaign_id:string;run_ordinal:number;scenario:ScenarioId;scenario_generation:number;issued_by:string;issued_wall_ms:number;command_digest:string};
export type RunStartPrepareV1={schema:'RunStartPrepareV1';campaign_run_token:string;scenario_digest:string;generation:number;issued_by:string;issued_wall_ms:number;calibration_id:string;calibration_hash:string;calibration_generation:number;topology_hash:string;cohort:string[]};
export type RunStartReadyV1={schema:'RunStartReadyV1';node_id:string;campaign_run_token:string;generation:number;scenario_digest:string;calibration_id:string;calibration_hash:string;calibration_generation:number;topology_hash:string;authority_identity_digest:string};
export type RunStartCommitV1={schema:'RunStartCommitV1';campaign_run_token:string;generation:number;scenario_digest:string;readiness_digest:string;committed_by:string;committed_wall_ms:number};
export type FinalDecisionCandidateV1={schema:'FinalDecisionCandidateV1';decision_id:string;decision_digest:string;decision_sequence:number;replay_hash:string;replay_artifact_id:string;prediction:string;contributing_nodes:number;contributing_links:number;physical_baselines:number;calibration_id:string;calibration_hash:string;calibration_generation:number;topology_hash:string;authority_identity_digest:string};
export type RunFreezePrepareV2={schema:'RunFreezePrepareV2';campaign_run_token:string;scenario_digest:string;generation:number;issued_by:string;issued_wall_ms:number;candidate:FinalDecisionCandidateV1};
export type SnapshotReadyV2={schema:'SnapshotReadyV2';node_id:string;campaign_run_token:string;scenario_digest:string;generation:number;authority_identity_digest:string;replay_hash:string;replay_artifact_id:string;calibration_id:string;calibration_hash:string;calibration_generation:number;topology_hash:string};
export type RunFreezeCommitV2={schema:'RunFreezeCommitV2';campaign_run_token:string;scenario_digest:string;generation:number;authority_identity_digest:string;readiness_digest:string;committed_by:string;committed_wall_ms:number};

type State={command:ScenarioCommandV1|null;commandGeneration:number;runOrdinal:number;startPrepare:RunStartPrepareV1|null;startCommit:RunStartCommitV1|null;freezePrepare:RunFreezePrepareV2|null;freezeCommit:RunFreezeCommitV2|null};
const states=new Map<string,State>();
function fresh():State{return{command:null,commandGeneration:0,runOrdinal:0,startPrepare:null,startCommit:null,freezePrepare:null,freezeCommit:null}}
function canonical(v:any):string{if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return'['+v.map(canonical).join(',')+']';return'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}'}
function sha(v:unknown){return BodyFinderNative.sha256Text(typeof v==='string'?v:canonical(v))}
function session(nodes:Advertisement[]){const c=new Map<string,number>();for(const n of nodes){if(n.protocol_version===2&&n.session_id)c.set(String(n.session_id),(c.get(String(n.session_id))??0)+1)}return[...c.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))[0]?.[0]??'body-finder-lab'}
function cohort(nodes:Advertisement[]){return[...new Set(nodes.filter(n=>n.protocol_version===2&&n.node_id).map(n=>String(n.node_id)))].sort().slice(0,3)}
function scope(nodes:Advertisement[],localId:string|null){return`${session(nodes)}::${localId??'unknown'}`}
function st(nodes:Advertisement[],localId:string|null){const k=scope(nodes,localId);let s=states.get(k);if(!s){s=fresh();states.set(k,s)}return s}
function coordinatorNode(nodes:Advertisement[],id:string|null){return id?nodes.find(n=>n.node_id===id):undefined}
function topologyHash(cal:any){return String(cal?.topology_hash??(cal?.topology_fingerprint?sha(String(cal.topology_fingerprint)):'')??'')}
function calibrationIdentity(cal:any){return{calibration_id:String(cal?.calibration_id??''),calibration_hash:String(cal?.calibration_hash??''),calibration_generation:Number(cal?.calibration_generation??cal?.generation??0),topology_hash:topologyHash(cal)}}
function artifactComplete(nodes:Advertisement[],coordinatorId:string|null,localId:string|null,id:string,hash:string){if(!id||!hash)return false;if(coordinatorId===localId)return true;const n=coordinatorNode(nodes,coordinatorId);const meta=(n as any)?.artifact_cache_meta_v1?.[id];return Boolean(meta?.complete&&String(meta?.artifact_sha256??'')===hash)}
function syncScenario(nodes:Advertisement[],coordinatorId:string|null,localId:string|null){const s=st(nodes,localId);if(!coordinatorId||coordinatorId===localId)return;const remote=(coordinatorNode(nodes,coordinatorId)?.control_plane as any)?.scenario_command_v1 as ScenarioCommandV1|undefined;if(!remote||remote.schema!=='ScenarioCommandV1'||remote.issued_by!==coordinatorId||!remote.command_digest)return;const material={campaign_id:remote.campaign_id,run_ordinal:Number(remote.run_ordinal),scenario:remote.scenario,scenario_generation:Number(remote.scenario_generation),issued_by:remote.issued_by,issued_wall_ms:Number(remote.issued_wall_ms)};if(sha(material)!==remote.command_digest)return;if(!s.command||remote.scenario_generation>s.command.scenario_generation||(remote.scenario_generation===s.command.scenario_generation&&remote.command_digest!==s.command.command_digest)){s.command=remote;s.commandGeneration=Math.max(s.commandGeneration,remote.scenario_generation);s.runOrdinal=Math.max(s.runOrdinal,remote.run_ordinal);s.startPrepare=null;s.startCommit=null;s.freezePrepare=null;s.freezeCommit=null}}

export function issueScenarioCommand(nodes:Advertisement[],coordinatorId:string|null,localId:string|null,scenario:ScenarioId){if(!localId||coordinatorId!==localId)throw new Error('SCENARIO_COMMAND_COORDINATOR_ONLY');const ids=cohort(nodes);if(ids.length!==3||!ids.includes(localId))throw new Error('SCENARIO_COMMAND_REQUIRES_3_NODE_COHORT');const s=st(nodes,localId);s.commandGeneration+=1;s.runOrdinal+=1;const issued_wall_ms=Date.now();const material={campaign_id:session(nodes),run_ordinal:s.runOrdinal,scenario,scenario_generation:s.commandGeneration,issued_by:localId,issued_wall_ms};s.command={schema:'ScenarioCommandV1',...material,command_digest:sha(material)};s.startPrepare=null;s.startCommit=null;s.freezePrepare=null;s.freezeCommit=null;return s.command}
export function getScenarioCommandStatus(nodes:Advertisement[],coordinatorId:string|null,localId:string|null){syncScenario(nodes,coordinatorId,localId);const s=st(nodes,localId),ids=cohort(nodes),c=s.command;const ackMatrix=ids.map(id=>{if(!c)return{node_id:id,acknowledged:false};if(id===localId)return{node_id:id,acknowledged:true,digest:c.command_digest};const a=(nodes.find(x=>x.node_id===id)?.control_plane as any)?.scenario_ack_v1;return{node_id:id,acknowledged:Boolean(a&&a.schema==='ScenarioAckV1'&&a.node_id===id&&a.command_digest===c.command_digest&&Number(a.scenario_generation)===c.scenario_generation),digest:a?.command_digest??null}});return{schema:'ScenarioStatusV1',command:c,ack_matrix:ackMatrix,ack_count:ackMatrix.filter(x=>x.acknowledged).length,ready:Boolean(c&&ids.length===3&&ackMatrix.every(x=>x.acknowledged))}}

function syncStart(nodes:Advertisement[],coordinatorId:string|null,localId:string|null){const s=st(nodes,localId);if(!coordinatorId||coordinatorId===localId)return;const cp=coordinatorNode(nodes,coordinatorId)?.control_plane as any;const p=cp?.run_start_prepare_v1 as RunStartPrepareV1|undefined;if(p&&p.schema==='RunStartPrepareV1'&&s.command&&p.scenario_digest===s.command.command_digest&&(!s.startPrepare||p.generation>=s.startPrepare.generation))s.startPrepare=p;const c=cp?.run_start_commit_v1 as RunStartCommitV1|undefined;if(c&&c.schema==='RunStartCommitV1'&&s.startPrepare&&c.campaign_run_token===s.startPrepare.campaign_run_token&&c.generation===s.startPrepare.generation)s.startCommit=c}
function localStartReady(nodes:Advertisement[],localId:string|null,cal:any):RunStartReadyV1|null{const s=st(nodes,localId),p=s.startPrepare;if(!p||!localId)return null;const ci=calibrationIdentity(cal);if(String(cal?.state)!=='READY'&&String(cal?.state)!=='STALE_AUTHORITY')return null;if(cal?.distributed_calibration_ready!==true&&Number(cal?.ack_count??0)!==3)return null;if(ci.calibration_id!==p.calibration_id||ci.calibration_hash!==p.calibration_hash||ci.calibration_generation!==p.calibration_generation||ci.topology_hash!==p.topology_hash)return null;const authority_identity_digest=sha({campaign_run_token:p.campaign_run_token,scenario_digest:p.scenario_digest,...ci});return{schema:'RunStartReadyV1',node_id:localId,campaign_run_token:p.campaign_run_token,generation:p.generation,scenario_digest:p.scenario_digest,...ci,authority_identity_digest}}
export function requestRunStart(nodes:Advertisement[],coordinatorId:string|null,localId:string|null,cal:any){syncScenario(nodes,coordinatorId,localId);const s=st(nodes,localId);if(!localId||coordinatorId!==localId)throw new Error('RUN_START_COORDINATOR_ONLY');const ss=getScenarioCommandStatus(nodes,coordinatorId,localId);if(!ss.ready||ss.ack_count!==3||!s.command)throw new Error('RUN_START_SCENARIO_ACK_3_OF_3_REQUIRED');if(cal?.distributed_calibration_ready!==true&&Number(cal?.ack_count??0)!==3)throw new Error('RUN_START_CALIBRATION_ACK_3_OF_3_REQUIRED');const ci=calibrationIdentity(cal);if(!ci.calibration_id||!ci.calibration_hash||!ci.topology_hash)throw new Error('RUN_START_CALIBRATION_IDENTITY_MISSING');const generation=(s.startPrepare?.generation??0)+1;const issued_wall_ms=Date.now();const campaign_run_token=sha({session_id:session(nodes),scenario_digest:s.command.command_digest,scenario_generation:s.command.scenario_generation,calibration:ci,cohort:cohort(nodes),generation,issued_wall_ms});s.startPrepare={schema:'RunStartPrepareV1',campaign_run_token,scenario_digest:s.command.command_digest,generation,issued_by:localId,issued_wall_ms,...ci,cohort:cohort(nodes)};s.startCommit=null;s.freezePrepare=null;s.freezeCommit=null;return s.startPrepare}
export function getRunStartBarrierStatus(nodes:Advertisement[],coordinatorId:string|null,localId:string|null,cal:any){syncScenario(nodes,coordinatorId,localId);syncStart(nodes,coordinatorId,localId);const s=st(nodes,localId),ids=cohort(nodes),local=localStartReady(nodes,localId,cal),ready:RunStartReadyV1[]=[];for(const id of ids){if(id===localId&&local)ready.push(local);else{const a=(nodes.find(n=>n.node_id===id)?.control_plane as any)?.run_start_ready_v1 as RunStartReadyV1|undefined;if(a&&a.schema==='RunStartReadyV1'&&s.startPrepare&&a.campaign_run_token===s.startPrepare.campaign_run_token&&a.generation===s.startPrepare.generation&&a.scenario_digest===s.startPrepare.scenario_digest)ready.push(a)}}const parity=ready.length===3&&new Set(ready.map(r=>r.authority_identity_digest)).size===1;if(coordinatorId===localId&&s.startPrepare&&parity&&!s.startCommit){s.startCommit={schema:'RunStartCommitV1',campaign_run_token:s.startPrepare.campaign_run_token,generation:s.startPrepare.generation,scenario_digest:s.startPrepare.scenario_digest,readiness_digest:sha(ready.slice().sort((a,b)=>a.node_id.localeCompare(b.node_id))),committed_by:localId!,committed_wall_ms:Date.now()}}return{schema:'RunStartBarrierV1',prepare:s.startPrepare,local_ready:local,ready_count:ready.length,ready_nodes:ready.map(r=>r.node_id).sort(),ready_parity:parity,commit:s.startCommit,committed:Boolean(s.startCommit&&s.startPrepare&&s.startCommit.campaign_run_token===s.startPrepare.campaign_run_token)}}

function candidateFrom(authority:any,cal:any):FinalDecisionCandidateV1|null{const d=authority?.decision??authority?.authoritative_presence??authority;const ci=calibrationIdentity(cal);if(!d?.decision_id||!d?.canonical_digest||!d?.canonical_replay_input)return null;if(Number(d?.contributing_nodes??0)<3||Number(d?.contributing_links??0)<6||Number(d?.physical_baselines??0)<3)return null;const replay_hash=sha(d.canonical_replay_input),replay_artifact_id=`decision-final:${String(d.decision_id)}`;const material={decision_id:String(d.decision_id),decision_digest:String(d.canonical_digest),decision_sequence:Number(d.decision_sequence??0),replay_hash,replay_artifact_id,prediction:String(d.prediction??'INDETERMINATE'),contributing_nodes:Number(d.contributing_nodes),contributing_links:Number(d.contributing_links),physical_baselines:Number(d.physical_baselines),...ci};return{schema:'FinalDecisionCandidateV1',...material,authority_identity_digest:sha(material)}}
function syncFreeze(nodes:Advertisement[],coordinatorId:string|null,localId:string|null){const s=st(nodes,localId);if(!coordinatorId||coordinatorId===localId)return;const cp=coordinatorNode(nodes,coordinatorId)?.control_plane as any;const p=cp?.run_freeze_prepare_v2 as RunFreezePrepareV2|undefined;if(p&&p.schema==='RunFreezePrepareV2'&&s.startCommit&&p.campaign_run_token===s.startCommit.campaign_run_token&&(!s.freezePrepare||p.generation>=s.freezePrepare.generation))s.freezePrepare=p;const c=cp?.run_freeze_commit_v2 as RunFreezeCommitV2|undefined;if(c&&c.schema==='RunFreezeCommitV2'&&s.freezePrepare&&c.campaign_run_token===s.freezePrepare.campaign_run_token&&c.generation===s.freezePrepare.generation&&c.authority_identity_digest===s.freezePrepare.candidate.authority_identity_digest)s.freezeCommit=c}
export function requestRunFreeze(nodes:Advertisement[],coordinatorId:string|null,localId:string|null,authority:any,cal:any){syncScenario(nodes,coordinatorId,localId);syncStart(nodes,coordinatorId,localId);const s=st(nodes,localId);if(!localId||coordinatorId!==localId)throw new Error('RUN_FREEZE_COORDINATOR_ONLY');if(!s.startCommit)throw new Error('RUN_FREEZE_START_COMMIT_REQUIRED');const candidate=candidateFrom(authority,cal);if(!candidate)throw new Error('RUN_FREEZE_FINAL_DECISION_CANDIDATE_NOT_ADMISSIBLE');if(candidate.calibration_id!==s.startPrepare?.calibration_id||candidate.calibration_hash!==s.startPrepare?.calibration_hash||candidate.calibration_generation!==s.startPrepare?.calibration_generation)throw new Error('RUN_FREEZE_CALIBRATION_MISMATCH');const generation=(s.freezePrepare?.generation??0)+1;s.freezePrepare={schema:'RunFreezePrepareV2',campaign_run_token:s.startCommit.campaign_run_token,scenario_digest:s.startCommit.scenario_digest,generation,issued_by:localId,issued_wall_ms:Date.now(),candidate};s.freezeCommit=null;return s.freezePrepare}
function localFreezeReady(nodes:Advertisement[],coordinatorId:string|null,localId:string|null,cal:any):SnapshotReadyV2|null{const s=st(nodes,localId),p=s.freezePrepare;if(!p||!localId)return null;const ci=calibrationIdentity(cal),c=p.candidate;if(ci.calibration_id!==c.calibration_id||ci.calibration_hash!==c.calibration_hash||ci.calibration_generation!==c.calibration_generation||ci.topology_hash!==c.topology_hash)return null;if(!artifactComplete(nodes,coordinatorId,localId,c.replay_artifact_id,c.replay_hash))return null;return{schema:'SnapshotReadyV2',node_id:localId,campaign_run_token:p.campaign_run_token,scenario_digest:p.scenario_digest,generation:p.generation,authority_identity_digest:c.authority_identity_digest,replay_hash:c.replay_hash,replay_artifact_id:c.replay_artifact_id,...ci}}
export function getFreezeBarrierStatus(nodes:Advertisement[],coordinatorId:string|null,localId:string|null,_authority:any,cal:any){syncScenario(nodes,coordinatorId,localId);syncStart(nodes,coordinatorId,localId);syncFreeze(nodes,coordinatorId,localId);const s=st(nodes,localId),ids=cohort(nodes),local=localFreezeReady(nodes,coordinatorId,localId,cal),ready:SnapshotReadyV2[]=[];for(const id of ids){if(id===localId&&local)ready.push(local);else{const a=(nodes.find(n=>n.node_id===id)?.control_plane as any)?.snapshot_ready_v2 as SnapshotReadyV2|undefined;if(a&&a.schema==='SnapshotReadyV2'&&s.freezePrepare&&a.campaign_run_token===s.freezePrepare.campaign_run_token&&a.generation===s.freezePrepare.generation&&a.authority_identity_digest===s.freezePrepare.candidate.authority_identity_digest)ready.push(a)}}const parity=ready.length===3&&s.freezePrepare!=null&&ready.every(r=>r.authority_identity_digest===s.freezePrepare!.candidate.authority_identity_digest&&r.replay_hash===s.freezePrepare!.candidate.replay_hash);if(coordinatorId===localId&&s.freezePrepare&&parity&&!s.freezeCommit){s.freezeCommit={schema:'RunFreezeCommitV2',campaign_run_token:s.freezePrepare.campaign_run_token,scenario_digest:s.freezePrepare.scenario_digest,generation:s.freezePrepare.generation,authority_identity_digest:s.freezePrepare.candidate.authority_identity_digest,readiness_digest:sha(ready.slice().sort((a,b)=>a.node_id.localeCompare(b.node_id))),committed_by:localId!,committed_wall_ms:Date.now()}}return{schema:'SnapshotFreezeV2',prepare:s.freezePrepare,local_ready:local,ready_count:ready.length,ready_nodes:ready.map(r=>r.node_id).sort(),ready_parity:parity,commit:s.freezeCommit,committed:Boolean(s.freezeCommit&&s.freezePrepare&&s.freezeCommit.campaign_run_token===s.freezePrepare.campaign_run_token)}}

export function getCampaignControlPublication(nodes:Advertisement[],coordinatorId:string|null,localId:string|null,authority:any,cal:any){const sstat=getScenarioCommandStatus(nodes,coordinatorId,localId),start=getRunStartBarrierStatus(nodes,coordinatorId,localId,cal),freeze=getFreezeBarrierStatus(nodes,coordinatorId,localId,authority,cal),s=st(nodes,localId),artifacts:any[]=[];if(coordinatorId===localId&&s.freezePrepare){const d=authority?.decision??authority?.authoritative_presence??authority;if(d?.canonical_replay_input&&s.freezePrepare.candidate?.replay_artifact_id)artifacts.push({artifact_id:s.freezePrepare.candidate.replay_artifact_id,artifact_type:'DECISION_FINAL_REPLAY_V1',generation:s.freezePrepare.generation,priority:'DECISION_FINAL',supersedes_artifact_id:null,payload:d.canonical_replay_input})}const c=sstat.command;return{scenario_command_v1:coordinatorId===localId?c:null,scenario_ack_v1:c&&localId?{schema:'ScenarioAckV1',node_id:localId,scenario_generation:c.scenario_generation,command_digest:c.command_digest}:null,run_start_prepare_v1:coordinatorId===localId?start.prepare:null,run_start_ready_v1:start.local_ready,run_start_commit_v1:coordinatorId===localId?start.commit:null,run_freeze_prepare_v2:coordinatorId===localId?freeze.prepare:null,snapshot_ready_v2:freeze.local_ready,run_freeze_commit_v2:coordinatorId===localId?freeze.commit:null,artifact_payloads_v1:artifacts}}
