import BodyFinderNative from '../modules/body-finder-native';
import { Advertisement } from './autogeometry';
import { getAuthorityStatus } from './authority';

export type ScenarioId='SMOKE_CAL_EMPTY'|'HUMAN_MOVING'|'EMPTY_CAL'|'EMPTY_TEST'|'HUMAN_STATIONARY_CENTER'|'HUMAN_NEAR_LENOVO'|'HUMAN_NEAR_PIXEL10'|'HUMAN_NEAR_PIXEL7'|'HUMAN_OUTSIDE'|'NON_HUMAN_MOTION';
export type ScenarioCommandV1={schema:'ScenarioCommandV1';campaign_id:string;run_ordinal:number;scenario:ScenarioId;scenario_generation:number;issued_by:string;issued_wall_ms:number;authority_view_digest:string;coordinator_generation:number;command_digest:string};
export type RunStartPrepareV1={schema:'RunStartPrepareV1';campaign_run_token:string;scenario_digest:string;generation:number;issued_by:string;issued_wall_ms:number;calibration_id:string;calibration_hash:string;calibration_generation:number;topology_hash:string;cohort:string[];authority_view_digest:string;coordinator_generation:number};
export type RunStartReadyV1={schema:'RunStartReadyV1';node_id:string;campaign_run_token:string;generation:number;scenario_digest:string;calibration_id:string;calibration_hash:string;calibration_generation:number;topology_hash:string;authority_view_digest:string;coordinator_generation:number;authority_identity_digest:string};
export type RunStartCommitV1={schema:'RunStartCommitV1';campaign_run_token:string;generation:number;scenario_digest:string;authority_view_digest:string;coordinator_generation:number;readiness_digest:string;committed_by:string;committed_wall_ms:number};
export type FinalDecisionCandidateV1={schema:'FinalDecisionCandidateV1';decision_id:string;decision_digest:string;decision_sequence:number;replay_hash:string;replay_artifact_id:string;prediction:string;contributing_nodes:number;contributing_links:number;physical_baselines:number;calibration_id:string;calibration_hash:string;calibration_generation:number;topology_hash:string;authority_identity_digest:string};
export type RunFreezePrepareV2={schema:'RunFreezePrepareV2';campaign_run_token:string;scenario_digest:string;generation:number;issued_by:string;issued_wall_ms:number;authority_view_digest:string;candidate:FinalDecisionCandidateV1};
export type SnapshotReadyV2={schema:'SnapshotReadyV2';node_id:string;campaign_run_token:string;scenario_digest:string;generation:number;authority_view_digest:string;authority_identity_digest:string;replay_hash:string;replay_artifact_id:string;calibration_id:string;calibration_hash:string;calibration_generation:number;topology_hash:string};
export type RunFreezeCommitV2={schema:'RunFreezeCommitV2';campaign_run_token:string;scenario_digest:string;generation:number;authority_view_digest:string;authority_identity_digest:string;readiness_digest:string;committed_by:string;committed_wall_ms:number};
type RunStartPrepareWireV2={v:'R2P';t:string;g:number;n:string;w:number;b:string};
type RunStartReadyWireV2={v:'R2R';t:string;g:number;n:string;b:string};
type RunStartCommitWireV2={v:'R2C';t:string;g:number;b:string;a:string;r:string;n:string;w:number};
type RunFreezePrepareWireV3={v:'F3P';t:string;g:number;n:string;w:number;b:string};
type RunFreezeReadyWireV3={v:'F3R';t:string;g:number;n:string;b:string};
type RunFreezeCommitWireV3={v:'F3C';t:string;g:number;b:string;r:string;n:string;w:number};
type State={authorityDigest:string|null;command:ScenarioCommandV1|null;commandGeneration:number;runOrdinal:number;startPrepare:RunStartPrepareV1|null;startCommit:RunStartCommitV1|null;freezePrepare:RunFreezePrepareV2|null;freezeCommit:RunFreezeCommitV2|null};
const states=new Map<string,State>();
function fresh():State{return{authorityDigest:null,command:null,commandGeneration:0,runOrdinal:0,startPrepare:null,startCommit:null,freezePrepare:null,freezeCommit:null}}
function canonical(v:any):string{if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return'['+v.map(canonical).join(',')+']';return'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}'}
function sha(v:unknown){return BodyFinderNative.sha256Text(typeof v==='string'?v:canonical(v))}
function session(nodes:Advertisement[]){const c=new Map<string,number>();for(const n of nodes){if(n.protocol_version===2&&n.session_id)c.set(String(n.session_id),(c.get(String(n.session_id))??0)+1)}return[...c.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))[0]?.[0]??'body-finder-lab'}
function cohort(nodes:Advertisement[]){return getAuthorityStatus(nodes,null).view?.cohort.map(x=>x.node_id)??[]}
function scope(nodes:Advertisement[],localId:string|null){return`${session(nodes)}::${localId??'unknown'}`}
function st(nodes:Advertisement[],localId:string|null){const k=scope(nodes,localId);let s=states.get(k);if(!s){s=fresh();states.set(k,s)}return s}
function bind(nodes:Advertisement[],localId:string|null,s:State){const a=getAuthorityStatus(nodes,localId),digest=a.view?.authority_view_digest??null;if(s.authorityDigest&&digest&&s.authorityDigest!==digest&&!s.startCommit){s.command=null;s.startPrepare=null;s.startCommit=null;s.freezePrepare=null;s.freezeCommit=null}s.authorityDigest=digest;return a}
function coordinatorNode(nodes:Advertisement[],id:string|null){return id?nodes.find(n=>n.node_id===id):undefined}
function topologyHash(cal:any){return String(cal?.topology_hash??(cal?.topology_fingerprint?sha(String(cal.topology_fingerprint)):'')??'')}
function calibrationIdentity(cal:any){return{calibration_id:String(cal?.calibration_id??''),calibration_hash:String(cal?.calibration_hash??''),calibration_generation:Number(cal?.calibration_generation??cal?.generation??0),topology_hash:topologyHash(cal)}}
function startPrepareBinding(p:RunStartPrepareV1){return sha({campaign_run_token:p.campaign_run_token,scenario_digest:p.scenario_digest,generation:p.generation,issued_by:p.issued_by,issued_wall_ms:p.issued_wall_ms,calibration_id:p.calibration_id,calibration_hash:p.calibration_hash,calibration_generation:p.calibration_generation,topology_hash:p.topology_hash,cohort:p.cohort.slice().sort(),authority_view_digest:p.authority_view_digest,coordinator_generation:p.coordinator_generation})}
function freezePrepareBinding(p:RunFreezePrepareV2){return sha({campaign_run_token:p.campaign_run_token,scenario_digest:p.scenario_digest,generation:p.generation,issued_by:p.issued_by,issued_wall_ms:p.issued_wall_ms,authority_view_digest:p.authority_view_digest,candidate:p.candidate})}
export function encodeRunStartPrepareWireV2(p:RunStartPrepareV1):RunStartPrepareWireV2{return{v:'R2P',t:p.campaign_run_token,g:p.generation,n:p.issued_by,w:p.issued_wall_ms,b:startPrepareBinding(p)}}
export function encodeRunStartReadyWireV2(r:RunStartReadyV1,p:RunStartPrepareV1):RunStartReadyWireV2{return{v:'R2R',t:r.campaign_run_token,g:r.generation,n:r.node_id,b:startPrepareBinding(p)}}
export function encodeRunStartCommitWireV2(c:RunStartCommitV1,p:RunStartPrepareV1):RunStartCommitWireV2{return{v:'R2C',t:c.campaign_run_token,g:c.generation,b:startPrepareBinding(p),a:c.authority_view_digest,r:c.readiness_digest,n:c.committed_by,w:c.committed_wall_ms}}
export function encodeRunFreezePrepareWireV3(p:RunFreezePrepareV2):RunFreezePrepareWireV3{return{v:'F3P',t:p.campaign_run_token,g:p.generation,n:p.issued_by,w:p.issued_wall_ms,b:freezePrepareBinding(p)}}
export function encodeRunFreezeReadyWireV3(r:SnapshotReadyV2,p:RunFreezePrepareV2):RunFreezeReadyWireV3{return{v:'F3R',t:r.campaign_run_token,g:r.generation,n:r.node_id,b:freezePrepareBinding(p)}}
export function encodeRunFreezeCommitWireV3(c:RunFreezeCommitV2,p:RunFreezePrepareV2):RunFreezeCommitWireV3{return{v:'F3C',t:c.campaign_run_token,g:c.generation,b:freezePrepareBinding(p),r:c.readiness_digest,n:c.committed_by,w:c.committed_wall_ms}}
function decodeStartPrepare(raw:any,nodes:Advertisement[],coordinatorId:string|null,localId:string|null,cal:any,s:State,a:any):RunStartPrepareV1|null{if(raw?.v!=='R2P'||!a.view||!s.command||!coordinatorId||raw.n!==coordinatorId)return null;const generation=Number(raw.g),issued_wall_ms=Number(raw.w),ci=calibrationIdentity(cal),ids=cohort(nodes).slice().sort();if(!Number.isSafeInteger(generation)||generation<=0||!Number.isFinite(issued_wall_ms)||ids.length!==3||!ci.calibration_id||!ci.calibration_hash||!ci.topology_hash)return null;const token=sha({session_id:session(nodes),scenario_digest:s.command.command_digest,calibration:ci,cohort:a.view.cohort,authority_view_digest:a.view.authority_view_digest,generation,issued_wall_ms});if(raw.t!==token)return null;const p:RunStartPrepareV1={schema:'RunStartPrepareV1',campaign_run_token:token,scenario_digest:s.command.command_digest,generation,issued_by:coordinatorId,issued_wall_ms,...ci,cohort:ids,authority_view_digest:a.view.authority_view_digest,coordinator_generation:a.view.coordinator_generation};return raw.b===startPrepareBinding(p)?p:null}
function decodeStartReady(raw:any,p:RunStartPrepareV1,ids:string[]):RunStartReadyV1|null{if(raw?.v!=='R2R'||raw.t!==p.campaign_run_token||Number(raw.g)!==p.generation||!ids.includes(String(raw.n))||raw.b!==startPrepareBinding(p))return null;const ci={calibration_id:p.calibration_id,calibration_hash:p.calibration_hash,calibration_generation:p.calibration_generation,topology_hash:p.topology_hash},authority_identity_digest=sha({campaign_run_token:p.campaign_run_token,scenario_digest:p.scenario_digest,authority_view_digest:p.authority_view_digest,...ci});return{schema:'RunStartReadyV1',node_id:String(raw.n),campaign_run_token:p.campaign_run_token,generation:p.generation,scenario_digest:p.scenario_digest,...ci,authority_view_digest:p.authority_view_digest,coordinator_generation:p.coordinator_generation,authority_identity_digest}}
function decodeStartCommit(raw:any,p:RunStartPrepareV1):RunStartCommitV1|null{if(raw?.v!=='R2C'||raw.t!==p.campaign_run_token||Number(raw.g)!==p.generation||raw.b!==startPrepareBinding(p)||raw.a!==p.authority_view_digest||typeof raw.r!=='string'||typeof raw.n!=='string'||!Number.isFinite(Number(raw.w)))return null;return{schema:'RunStartCommitV1',campaign_run_token:p.campaign_run_token,generation:p.generation,scenario_digest:p.scenario_digest,authority_view_digest:p.authority_view_digest,coordinator_generation:p.coordinator_generation,readiness_digest:String(raw.r),committed_by:String(raw.n),committed_wall_ms:Number(raw.w)}}
function decodeFreezePrepare(raw:any,nodes:Advertisement[],coordinatorId:string|null,localId:string|null,authority:any,cal:any,s:State,a:any):RunFreezePrepareV2|null{if(raw?.v!=='F3P'||!a.view||!s.startCommit||!coordinatorId||raw.n!==coordinatorId||raw.t!==s.startCommit.campaign_run_token)return null;const candidate=candidateFrom(authority,cal),generation=Number(raw.g),issued_wall_ms=Number(raw.w);if(!candidate||!Number.isSafeInteger(generation)||generation<=0||!Number.isFinite(issued_wall_ms))return null;const p:RunFreezePrepareV2={schema:'RunFreezePrepareV2',campaign_run_token:s.startCommit.campaign_run_token,scenario_digest:s.startCommit.scenario_digest,generation,issued_by:coordinatorId,issued_wall_ms,authority_view_digest:a.view.authority_view_digest,candidate};return raw.b===freezePrepareBinding(p)?p:null}
function decodeFreezeReady(raw:any,p:RunFreezePrepareV2,ids:string[]):SnapshotReadyV2|null{if(raw?.v!=='F3R'||raw.t!==p.campaign_run_token||Number(raw.g)!==p.generation||!ids.includes(String(raw.n))||raw.b!==freezePrepareBinding(p))return null;const c=p.candidate;return{schema:'SnapshotReadyV2',node_id:String(raw.n),campaign_run_token:p.campaign_run_token,scenario_digest:p.scenario_digest,generation:p.generation,authority_view_digest:p.authority_view_digest,authority_identity_digest:c.authority_identity_digest,replay_hash:c.replay_hash,replay_artifact_id:c.replay_artifact_id,calibration_id:c.calibration_id,calibration_hash:c.calibration_hash,calibration_generation:c.calibration_generation,topology_hash:c.topology_hash}}
function decodeFreezeCommit(raw:any,p:RunFreezePrepareV2):RunFreezeCommitV2|null{if(raw?.v!=='F3C'||raw.t!==p.campaign_run_token||Number(raw.g)!==p.generation||raw.b!==freezePrepareBinding(p)||typeof raw.r!=='string'||typeof raw.n!=='string'||!Number.isFinite(Number(raw.w)))return null;return{schema:'RunFreezeCommitV2',campaign_run_token:p.campaign_run_token,scenario_digest:p.scenario_digest,generation:p.generation,authority_view_digest:p.authority_view_digest,authority_identity_digest:p.candidate.authority_identity_digest,readiness_digest:String(raw.r),committed_by:String(raw.n),committed_wall_ms:Number(raw.w)}}
function artifactComplete(nodes:Advertisement[],coordinatorId:string|null,localId:string|null,id:string,hash:string){if(!id||!hash)return false;if(coordinatorId===localId)return true;const n=coordinatorNode(nodes,coordinatorId);const meta=(n as any)?.artifact_cache_meta_v1?.[id];return Boolean(meta?.complete&&String(meta?.artifact_sha256??'')===hash)}
function syncScenario(nodes:Advertisement[],coordinatorId:string|null,localId:string|null){const s=st(nodes,localId),a=bind(nodes,localId,s);if(!a.view||!coordinatorId||coordinatorId===localId)return;const remote=(coordinatorNode(nodes,coordinatorId)?.control_plane as any)?.scenario_command_v1 as ScenarioCommandV1|undefined;if(!remote||remote.schema!=='ScenarioCommandV1'||remote.issued_by!==coordinatorId||remote.authority_view_digest!==a.view.authority_view_digest||Number(remote.coordinator_generation)!==a.view.coordinator_generation)return;const material={campaign_id:remote.campaign_id,run_ordinal:Number(remote.run_ordinal),scenario:remote.scenario,scenario_generation:Number(remote.scenario_generation),issued_by:remote.issued_by,issued_wall_ms:Number(remote.issued_wall_ms),authority_view_digest:remote.authority_view_digest,coordinator_generation:Number(remote.coordinator_generation)};if(sha(material)!==remote.command_digest)return;if(!s.command||remote.scenario_generation>s.command.scenario_generation||(remote.scenario_generation===s.command.scenario_generation&&remote.command_digest!==s.command.command_digest)){s.command=remote;s.commandGeneration=Math.max(s.commandGeneration,remote.scenario_generation);s.runOrdinal=Math.max(s.runOrdinal,remote.run_ordinal);s.startPrepare=null;s.startCommit=null;s.freezePrepare=null;s.freezeCommit=null}}
export function issueScenarioCommand(nodes:Advertisement[],coordinatorId:string|null,localId:string|null,scenario:ScenarioId){const s=st(nodes,localId),a=bind(nodes,localId,s);if(!a.view||!a.consensus||a.ack_count!==3)throw new Error('SCENARIO_AUTHORITY_ACK_3_OF_3_REQUIRED');if(!localId||coordinatorId!==localId||a.view.elected_coordinator!==localId)throw new Error('SCENARIO_COMMAND_COORDINATOR_ONLY');s.commandGeneration+=1;s.runOrdinal+=1;const issued_wall_ms=Date.now(),material={campaign_id:session(nodes),run_ordinal:s.runOrdinal,scenario,scenario_generation:s.commandGeneration,issued_by:localId,issued_wall_ms,authority_view_digest:a.view.authority_view_digest,coordinator_generation:a.view.coordinator_generation};s.command={schema:'ScenarioCommandV1',...material,command_digest:sha(material)};s.startPrepare=null;s.startCommit=null;s.freezePrepare=null;s.freezeCommit=null;return s.command}
export function getScenarioCommandStatus(nodes:Advertisement[],coordinatorId:string|null,localId:string|null){syncScenario(nodes,coordinatorId,localId);const s=st(nodes,localId),a=bind(nodes,localId,s),ids=cohort(nodes),c=s.command;const ack_matrix=ids.map(id=>{if(!c)return{node_id:id,acknowledged:false};if(id===localId)return{node_id:id,acknowledged:Boolean(a.view&&c.authority_view_digest===a.view.authority_view_digest),digest:c.command_digest};const x=(nodes.find(n=>n.node_id===id)?.control_plane as any)?.scenario_ack_v1;return{node_id:id,acknowledged:Boolean(x?.schema==='ScenarioAckV1'&&x?.node_id===id&&x?.command_digest===c.command_digest&&Number(x?.scenario_generation)===c.scenario_generation&&x?.authority_view_digest===c.authority_view_digest),digest:x?.command_digest??null}});const ack_count=ack_matrix.filter(x=>x.acknowledged).length;return{schema:'ScenarioStatusV1',command:c,ack_matrix,ack_count,ready:Boolean(c&&a.consensus&&ids.length===3&&ack_count===3)}}
function syncStart(nodes:Advertisement[],coordinatorId:string|null,localId:string|null,cal:any){const s=st(nodes,localId),a=bind(nodes,localId,s);if(!a.view||!coordinatorId||coordinatorId===localId)return;const cp=coordinatorNode(nodes,coordinatorId)?.control_plane as any,p=decodeStartPrepare(cp?.run_start_prepare_v1,nodes,coordinatorId,localId,cal,s,a);if(p&&(!s.startPrepare||p.generation>=s.startPrepare.generation))s.startPrepare=p;const c=s.startPrepare?decodeStartCommit(cp?.run_start_commit_v1,s.startPrepare):null;if(c&&c.committed_by===coordinatorId)s.startCommit=c}
function localStartReady(nodes:Advertisement[],localId:string|null,cal:any):RunStartReadyV1|null{const s=st(nodes,localId),a=bind(nodes,localId,s),p=s.startPrepare;if(!p||!localId||!a.view||!a.consensus)return null;const ci=calibrationIdentity(cal);if(String(cal?.state)!=='READY'&&String(cal?.state)!=='STALE_AUTHORITY')return null;if(Number(cal?.peer_ack_count??0)!==3||cal?.distributed_calibration_ready!==true||String(cal?.authority_digest??'')!==a.view.authority_view_digest)return null;if(ci.calibration_id!==p.calibration_id||ci.calibration_hash!==p.calibration_hash||ci.calibration_generation!==p.calibration_generation||ci.topology_hash!==p.topology_hash||p.authority_view_digest!==a.view.authority_view_digest)return null;const authority_identity_digest=sha({campaign_run_token:p.campaign_run_token,scenario_digest:p.scenario_digest,authority_view_digest:p.authority_view_digest,...ci});return{schema:'RunStartReadyV1',node_id:localId,campaign_run_token:p.campaign_run_token,generation:p.generation,scenario_digest:p.scenario_digest,...ci,authority_view_digest:p.authority_view_digest,coordinator_generation:p.coordinator_generation,authority_identity_digest}}
export function requestRunStart(nodes:Advertisement[],coordinatorId:string|null,localId:string|null,cal:any){syncScenario(nodes,coordinatorId,localId);const s=st(nodes,localId),a=bind(nodes,localId,s);if(!a.view||!a.consensus||a.ack_count!==3)throw new Error('RUN_START_AUTHORITY_ACK_3_OF_3_REQUIRED');if(!localId||coordinatorId!==localId||a.view.elected_coordinator!==localId)throw new Error('RUN_START_COORDINATOR_ONLY');const ss=getScenarioCommandStatus(nodes,coordinatorId,localId);if(!ss.ready||ss.ack_count!==3||!s.command)throw new Error('RUN_START_SCENARIO_ACK_3_OF_3_REQUIRED');if(cal?.distributed_calibration_ready!==true||Number(cal?.peer_ack_count??0)!==3)throw new Error('RUN_START_CALIBRATION_ACK_3_OF_3_REQUIRED');if(String(cal?.authority_digest??'')!==a.view.authority_view_digest)throw new Error('RUN_START_CALIBRATION_AUTHORITY_MISMATCH');const ci=calibrationIdentity(cal);if(!ci.calibration_id||!ci.calibration_hash||!ci.topology_hash)throw new Error('RUN_START_CALIBRATION_IDENTITY_MISSING');const generation=(s.startPrepare?.generation??0)+1,issued_wall_ms=Date.now(),campaign_run_token=sha({session_id:session(nodes),scenario_digest:s.command.command_digest,calibration:ci,cohort:a.view.cohort,authority_view_digest:a.view.authority_view_digest,generation,issued_wall_ms});s.startPrepare={schema:'RunStartPrepareV1',campaign_run_token,scenario_digest:s.command.command_digest,generation,issued_by:localId,issued_wall_ms,...ci,cohort:cohort(nodes),authority_view_digest:a.view.authority_view_digest,coordinator_generation:a.view.coordinator_generation};s.startCommit=null;s.freezePrepare=null;s.freezeCommit=null;return s.startPrepare}
export function getRunStartBarrierStatus(nodes:Advertisement[],coordinatorId:string|null,localId:string|null,cal:any){syncScenario(nodes,coordinatorId,localId);syncStart(nodes,coordinatorId,localId,cal);const s=st(nodes,localId),a=bind(nodes,localId,s),ids=cohort(nodes),local=localStartReady(nodes,localId,cal),ready:RunStartReadyV1[]=[];for(const id of ids){if(id===localId&&local)ready.push(local);else if(s.startPrepare){const raw=(nodes.find(n=>n.node_id===id)?.control_plane as any)?.run_start_ready_v1,x=decodeStartReady(raw,s.startPrepare,ids);if(x&&x.node_id===id)ready.push(x)}}const parity=ready.length===3&&new Set(ready.map(r=>r.authority_identity_digest)).size===1&&Boolean(a.view&&ready.every(r=>r.authority_view_digest===a.view!.authority_view_digest));if(coordinatorId===localId&&a.view&&a.consensus&&s.startPrepare&&parity&&!s.startCommit)s.startCommit={schema:'RunStartCommitV1',campaign_run_token:s.startPrepare.campaign_run_token,generation:s.startPrepare.generation,scenario_digest:s.startPrepare.scenario_digest,authority_view_digest:a.view.authority_view_digest,coordinator_generation:a.view.coordinator_generation,readiness_digest:sha(ready.slice().sort((x,y)=>x.node_id.localeCompare(y.node_id))),committed_by:localId!,committed_wall_ms:Date.now()};return{schema:'RunStartBarrierV1',wire_schema:'RunStartWireV2',authority_view_digest:a.view?.authority_view_digest??null,authority_ack_count:a.ack_count,prepare:s.startPrepare,local_ready:local,ready_count:ready.length,ready_nodes:ready.map(r=>r.node_id).sort(),ready_parity:parity,commit:s.startCommit,committed:Boolean(s.startCommit&&s.startPrepare&&s.startCommit.campaign_run_token===s.startPrepare.campaign_run_token)}}
function candidateFrom(authority:any,cal:any):FinalDecisionCandidateV1|null{const d=authority?.decision??authority?.authoritative_presence??authority,ci=calibrationIdentity(cal);if(!d?.decision_id||!d?.canonical_digest||!d?.canonical_replay_input)return null;if(Number(d?.contributing_nodes??0)<3||Number(d?.contributing_links??0)<6||Number(d?.physical_baselines??0)<3)return null;const replay_hash=sha(d.canonical_replay_input),replay_artifact_id=`decision-final:${String(d.decision_id)}`,material={decision_id:String(d.decision_id),decision_digest:String(d.canonical_digest),decision_sequence:Number(d.decision_sequence??0),replay_hash,replay_artifact_id,prediction:String(d.prediction??'INDETERMINATE'),contributing_nodes:Number(d.contributing_nodes),contributing_links:Number(d.contributing_links),physical_baselines:Number(d.physical_baselines),...ci};return{schema:'FinalDecisionCandidateV1',...material,authority_identity_digest:sha(material)}}
function syncFreeze(nodes:Advertisement[],coordinatorId:string|null,localId:string|null,authority:any,cal:any){const s=st(nodes,localId),a=bind(nodes,localId,s);if(!a.view||!coordinatorId||coordinatorId===localId)return;const cp=coordinatorNode(nodes,coordinatorId)?.control_plane as any,p=decodeFreezePrepare(cp?.run_freeze_prepare_v2,nodes,coordinatorId,localId,authority,cal,s,a);if(p&&(!s.freezePrepare||p.generation>=s.freezePrepare.generation))s.freezePrepare=p;const c=s.freezePrepare?decodeFreezeCommit(cp?.run_freeze_commit_v2,s.freezePrepare):null;if(c&&c.committed_by===coordinatorId)s.freezeCommit=c}
export function requestRunFreeze(nodes:Advertisement[],coordinatorId:string|null,localId:string|null,authority:any,cal:any){syncScenario(nodes,coordinatorId,localId);syncStart(nodes,coordinatorId,localId,cal);const s=st(nodes,localId),a=bind(nodes,localId,s);if(!localId||coordinatorId!==localId||!a.view||!a.consensus)throw new Error('RUN_FREEZE_AUTHORITY_REQUIRED');if(!s.startCommit||s.startCommit.authority_view_digest!==a.view.authority_view_digest)throw new Error('RUN_FREEZE_START_COMMIT_REQUIRED');const candidate=candidateFrom(authority,cal);if(!candidate)throw new Error('RUN_FREEZE_FINAL_DECISION_CANDIDATE_NOT_ADMISSIBLE');if(candidate.calibration_id!==s.startPrepare?.calibration_id||candidate.calibration_hash!==s.startPrepare?.calibration_hash||candidate.calibration_generation!==s.startPrepare?.calibration_generation)throw new Error('RUN_FREEZE_CALIBRATION_MISMATCH');const generation=(s.freezePrepare?.generation??0)+1;s.freezePrepare={schema:'RunFreezePrepareV2',campaign_run_token:s.startCommit.campaign_run_token,scenario_digest:s.startCommit.scenario_digest,generation,issued_by:localId,issued_wall_ms:Date.now(),authority_view_digest:a.view.authority_view_digest,candidate};s.freezeCommit=null;return s.freezePrepare}
function localFreezeReady(nodes:Advertisement[],coordinatorId:string|null,localId:string|null,cal:any):SnapshotReadyV2|null{const s=st(nodes,localId),a=bind(nodes,localId,s),p=s.freezePrepare;if(!p||!localId||!a.view||p.authority_view_digest!==a.view.authority_view_digest)return null;const ci=calibrationIdentity(cal),c=p.candidate;if(ci.calibration_id!==c.calibration_id||ci.calibration_hash!==c.calibration_hash||ci.calibration_generation!==c.calibration_generation||ci.topology_hash!==c.topology_hash)return null;if(!artifactComplete(nodes,coordinatorId,localId,c.replay_artifact_id,c.replay_hash))return null;return{schema:'SnapshotReadyV2',node_id:localId,campaign_run_token:p.campaign_run_token,scenario_digest:p.scenario_digest,generation:p.generation,authority_view_digest:a.view.authority_view_digest,authority_identity_digest:c.authority_identity_digest,replay_hash:c.replay_hash,replay_artifact_id:c.replay_artifact_id,...ci}}
export function getFreezeBarrierStatus(nodes:Advertisement[],coordinatorId:string|null,localId:string|null,authority:any,cal:any){syncScenario(nodes,coordinatorId,localId);syncStart(nodes,coordinatorId,localId,cal);syncFreeze(nodes,coordinatorId,localId,authority,cal);const s=st(nodes,localId),a=bind(nodes,localId,s),ids=cohort(nodes),local=localFreezeReady(nodes,coordinatorId,localId,cal),ready:SnapshotReadyV2[]=[];for(const id of ids){if(id===localId&&local)ready.push(local);else if(s.freezePrepare){const cp=nodes.find(n=>n.node_id===id)?.control_plane as any,raw=cp?.run_freeze_ready_v2??cp?.snapshot_ready_v2,x=decodeFreezeReady(raw,s.freezePrepare,ids);if(x&&x.node_id===id)ready.push(x)}}const parity=ready.length===3&&s.freezePrepare!=null&&a.view!=null&&ready.every(r=>r.authority_view_digest===a.view!.authority_view_digest&&r.authority_identity_digest===s.freezePrepare!.candidate.authority_identity_digest&&r.replay_hash===s.freezePrepare!.candidate.replay_hash);if(coordinatorId===localId&&s.freezePrepare&&a.view&&parity&&!s.freezeCommit)s.freezeCommit={schema:'RunFreezeCommitV2',campaign_run_token:s.freezePrepare.campaign_run_token,scenario_digest:s.freezePrepare.scenario_digest,generation:s.freezePrepare.generation,authority_view_digest:a.view.authority_view_digest,authority_identity_digest:s.freezePrepare.candidate.authority_identity_digest,readiness_digest:sha(ready.slice().sort((x,y)=>x.node_id.localeCompare(y.node_id))),committed_by:localId!,committed_wall_ms:Date.now()};return{schema:'SnapshotFreezeV2',wire_schema:'RunFreezeWireV3',authority_view_digest:a.view?.authority_view_digest??null,prepare:s.freezePrepare,local_ready:local,ready_count:ready.length,ready_nodes:ready.map(r=>r.node_id).sort(),ready_parity:parity,commit:s.freezeCommit,committed:Boolean(s.freezeCommit&&s.freezePrepare&&s.freezeCommit.campaign_run_token===s.freezePrepare.campaign_run_token)}}
export function getCampaignControlPublication(nodes:Advertisement[],coordinatorId:string|null,localId:string|null,authority:any,cal:any){const sstat=getScenarioCommandStatus(nodes,coordinatorId,localId),start=getRunStartBarrierStatus(nodes,coordinatorId,localId,cal),freeze=getFreezeBarrierStatus(nodes,coordinatorId,localId,authority,cal),s=st(nodes,localId),a=bind(nodes,localId,s),artifacts:any[]=[];if(coordinatorId===localId&&s.freezePrepare){const d=authority?.decision??authority?.authoritative_presence??authority;if(d?.canonical_replay_input&&s.freezePrepare.candidate?.replay_artifact_id)artifacts.push({artifact_id:s.freezePrepare.candidate.replay_artifact_id,artifact_type:'DECISION_FINAL_REPLAY_V1',generation:s.freezePrepare.generation,priority:'DECISION_FINAL',supersedes_artifact_id:null,payload:d.canonical_replay_input})}const c=sstat.command;return{scenario_command_v1:coordinatorId===localId?c:null,scenario_ack_v1:c&&localId&&a.view?{schema:'ScenarioAckV1',node_id:localId,scenario_generation:c.scenario_generation,command_digest:c.command_digest,authority_view_digest:a.view.authority_view_digest}:null,run_start_prepare_v1:coordinatorId===localId&&start.prepare?encodeRunStartPrepareWireV2(start.prepare):null,run_start_ready_v1:start.local_ready&&start.prepare?encodeRunStartReadyWireV2(start.local_ready,start.prepare):null,run_start_commit_v1:coordinatorId===localId&&start.commit&&start.prepare?encodeRunStartCommitWireV2(start.commit,start.prepare):null,run_freeze_prepare_v2:coordinatorId===localId&&freeze.prepare?encodeRunFreezePrepareWireV3(freeze.prepare):null,run_freeze_ready_v2:freeze.local_ready&&freeze.prepare?encodeRunFreezeReadyWireV3(freeze.local_ready,freeze.prepare):null,run_freeze_commit_v2:coordinatorId===localId&&freeze.commit&&freeze.prepare?encodeRunFreezeCommitWireV3(freeze.commit,freeze.prepare):null,artifact_payloads_v1:artifacts}}
