import { Advertisement } from './autogeometry';
import BodyFinderNative from '../modules/body-finder-native';
import { DETECTOR_ALGORITHM, DETECTOR_PARAMETER_HASH, DETECTOR_V5 } from './detectorParameters';

export type PresencePrediction = 'HUMAN_EVIDENCE' | 'NO_HUMAN_EVIDENCE' | 'INDETERMINATE';
export type CalibrationState = 'UNCALIBRATED'|'CALIBRATING'|'READY'|'INVALID'|'WAIT_COORDINATOR'|'STALE_AUTHORITY';
export type PresenceEstimate = {
  prediction: PresencePrediction; human_confidence: number; evidence_quality: string; fused_score: number;
  contributing_nodes: number; contributing_links: number; physical_baselines: number; reason: string;
  calibration_state: CalibrationState; calibration_id?: string|null; calibration_hash?: string|null;
  algorithm_version: string; parameter_hash: string; window_id: string; decision_id?: string; canonical_digest?: string;
  authoritative: boolean; source: string; [key: string]: any;
};
type Sample={receive_wall_ms:number;source_monotonic_ns:number|null;rssi_dbm:number};
type Link={link_id:string;observer_node_id:string;peer_node_id:string;samples:Sample[]};
type CalState={state:CalibrationState;generation:number;coordinator:string|null;topology:string|null;started:number;artifact:any|null;reason:string;expectedCohort:string[];publicationSequence:number;lastAuthorityWallMs:number;coordinatorGeneration:number;missingSince:Record<string,number>};
const HISTORY_MS=45_000;
const history=new Map<string,Sample[]>();
const lastSource=new Map<string,number>();
let cal:CalState={state:'UNCALIBRATED',generation:0,coordinator:null,topology:null,started:0,artifact:null,reason:'EMPTY_CAL_REQUIRED',expectedCohort:[],publicationSequence:0,lastAuthorityWallMs:0,coordinatorGeneration:0,missingSince:{}};

function fallback(reason:string,state:CalibrationState=cal.state):PresenceEstimate{return{prediction:'INDETERMINATE',human_confidence:0.5,evidence_quality:'LOW',fused_score:0,contributing_nodes:0,contributing_links:0,physical_baselines:0,reason,calibration_state:state,calibration_id:cal.artifact?.calibration_id??null,calibration_hash:cal.artifact?.calibration_hash??null,algorithm_version:DETECTOR_ALGORITHM,parameter_hash:DETECTOR_PARAMETER_HASH,window_id:String(Math.floor(Date.now()/2000)*2000),authoritative:false,source:'diagnostic_fail_closed'}}
function pair(a:string,b:string){return a<b?`${a}::${b}`:`${b}::${a}`}
function stableCohort(nodes:Advertisement[]){return [...new Set(nodes.filter(n=>n.protocol_version===2&&n.node_id).map(n=>String(n.node_id)))].sort()}
function cohortFingerprint(cohort:string[]){const directed:string[]=[];for(const a of cohort)for(const b of cohort)if(a!==b)directed.push(`${a}::${b}`);return cohort.join(',')+'|'+directed.sort().join(',')}
function ingest(nodes:Advertisement[]):Link[]{const now=Date.now();for(const n of nodes){for(const r of n.ranges??[]){const v=Number(r.rssi_dbm);if(!Number.isFinite(v)||v>0||v<-126)continue;const observer=String(r.observer_node_id||n.node_id||'');const peer=String(r.peer_node_id||'');if(!observer||!peer)continue;const id=`${observer}::${peer}`;const source=Number((r as any).source_observation_monotonic_ns??r.monotonic_ns??0);if(source>0&&lastSource.get(id)===source)continue;if(source>0)lastSource.set(id,source);const q=history.get(id)??[];q.push({receive_wall_ms:now,source_monotonic_ns:source>0?source:null,rssi_dbm:v});history.set(id,q.filter(s=>now-s.receive_wall_ms<=HISTORY_MS).slice(-180));}}return [...history.entries()].map(([id,samples])=>{const [observer,peer]=id.split('::');return{link_id:id,observer_node_id:observer,peer_node_id:peer,samples}}).sort((a,b)=>a.link_id.localeCompare(b.link_id))}
function expectedLinks(links:Link[],cohort:string[]){const ids=new Set<string>();for(const a of cohort)for(const b of cohort)if(a!==b)ids.add(`${a}::${b}`);return links.filter(l=>ids.has(l.link_id))}
function topology(links:Link[],cohort:string[]){const live=expectedLinks(links,cohort).filter(l=>l.samples.length&&Date.now()-l.samples.at(-1)!.receive_wall_ms<6000);const nodes=new Set(live.map(l=>l.observer_node_id));const baselines=new Set(live.map(l=>pair(l.observer_node_id,l.peer_node_id)));return{ok:nodes.size>=3&&live.length>=6&&baselines.size>=3,fingerprint:cohortFingerprint(cohort),links:live,nodes:nodes.size,baselines:baselines.size}}
function native(input:any){try{const out=JSON.parse(BodyFinderNative.evaluateHumanPresenceJson(JSON.stringify(input)));if(out?.error)throw new Error(String(out.error));return out}catch(e:any){return{error:String(e?.message??e)}}}

function publicationFrom(nodes:Advertisement[],coordinatorNodeId:string|null){const coordinator=nodes.find(n=>n.node_id===coordinatorNodeId);const p=(coordinator?.published_geometry as any)?.authoritative_presence?.calibration_publication_v5 ?? (coordinator?.published_geometry as any)?.calibration_publication_v5;return p??null}
function syncAuthoritativeCalibration(nodes:Advertisement[],coordinatorNodeId:string|null,localNodeId:string|null){if(!coordinatorNodeId||coordinatorNodeId===localNodeId)return;const p=publicationFrom(nodes,coordinatorNodeId),now=Date.now();if(p?.schema==='CalibrationPublicationV5'&&p?.detector_parameter_hash===DETECTOR_PARAMETER_HASH&&p?.artifact?.calibration_hash===p?.calibration_hash){cal={...cal,state:'READY',generation:Number(p.calibration_generation??0),coordinator:coordinatorNodeId,topology:String(p.topology_fingerprint),artifact:p.artifact,reason:'AUTHORITATIVE_CALIBRATION_MIRRORED',expectedCohort:Array.isArray(p.expected_cohort)?p.expected_cohort.map(String).sort():cal.expectedCohort,publicationSequence:Number(p.publication_sequence??0),lastAuthorityWallMs:now,coordinatorGeneration:Number(p.coordinator_generation??1)}}else if(cal.artifact&&cal.lastAuthorityWallMs&&now-cal.lastAuthorityWallMs>DETECTOR_V5.authorityPublicationLeaseMs){cal={...cal,state:'STALE_AUTHORITY',reason:'AUTHORITY_PUBLICATION_LEASE_EXPIRED_CALIBRATION_PRESERVED'}}}
function peerAckMatrix(nodes:Advertisement[]){const matrix:Record<string,boolean>={};for(const id of cal.expectedCohort)matrix[id]=id===cal.coordinator;const p=publicationFrom(nodes,cal.coordinator);if(p?.calibration_hash===cal.artifact?.calibration_hash){for(const n of nodes)if(cal.expectedCohort.includes(String(n.node_id)))matrix[String(n.node_id)]=true}return matrix}

export function beginSessionPresenceCalibration(nodes:Advertisement[],coordinatorNodeId:string|null,localNodeId:string|null){const links=ingest(nodes),cohort=stableCohort(nodes),t=topology(links,cohort);if(!coordinatorNodeId||coordinatorNodeId!==localNodeId){syncAuthoritativeCalibration(nodes,coordinatorNodeId,localNodeId);if(cal.artifact)return cal;cal={...cal,state:'WAIT_COORDINATOR',coordinator:coordinatorNodeId,reason:'CALIBRATION_MUST_BE_STARTED_ON_ELECTED_COORDINATOR'};return cal}if(cohort.length!==3||!t.ok){cal={...cal,state:'INVALID',coordinator:coordinatorNodeId,reason:'CALIBRATION_REQUIRES_3_NODES_6_LINKS_3_BASELINES'};return cal}cal={state:'CALIBRATING',generation:cal.generation+1,coordinator:coordinatorNodeId,topology:t.fingerprint,started:Date.now(),artifact:null,reason:'COLLECTING_SYNCHRONIZED_EMPTY_BASELINE',expectedCohort:cohort,publicationSequence:0,lastAuthorityWallMs:Date.now(),coordinatorGeneration:Math.max(1,cal.coordinatorGeneration+1),missingSince:{}};return cal}
export function getSessionPresenceCalibration(nodes:Advertisement[]=[]){const matrix=peerAckMatrix(nodes),expected=cal.expectedCohort.length||3;return{state:cal.state,generation:cal.generation,calibration_generation:cal.generation,coordinator_generation:cal.coordinatorGeneration,coordinator_node_id:cal.coordinator,topology_fingerprint:cal.topology,expected_cohort:cal.expectedCohort,started_wall_ms:cal.started,calibration_id:cal.artifact?.calibration_id??null,calibration_hash:cal.artifact?.calibration_hash??null,reason:cal.reason,publication_sequence:cal.publicationSequence,authority_lease_age_ms:cal.lastAuthorityWallMs?Date.now()-cal.lastAuthorityWallMs:null,peer_ack_matrix:matrix,distributed_calibration_ready:cal.state==='READY'&&Object.values(matrix).filter(Boolean).length>=expected}}
export function getCalibrationPublication(localNodeId:string|null){if(!cal.artifact||cal.coordinator!==localNodeId||cal.state!=='READY')return null;cal.publicationSequence+=1;return{schema:'CalibrationPublicationV5',session_id:cal.artifact.session_id,coordinator_id:cal.coordinator,coordinator_generation:cal.coordinatorGeneration,calibration_generation:cal.generation,calibration_id:cal.artifact.calibration_id,calibration_hash:cal.artifact.calibration_hash,topology_fingerprint:cal.topology,expected_cohort:cal.expectedCohort,publication_sequence:cal.publicationSequence,publication_wall_ms:Date.now(),detector_parameter_hash:DETECTOR_PARAMETER_HASH,state:'READY',reason:cal.reason,artifact:cal.artifact}}

function maybeFreeze(nodes:Advertisement[],coordinatorNodeId:string|null,localNodeId:string|null,links:Link[]){if(cal.state!=='CALIBRATING'||coordinatorNodeId!==localNodeId)return;if(Date.now()-cal.started>DETECTOR_V5.calibrationTimeoutMs){cal={...cal,state:'INVALID',reason:'CALIBRATION_INSUFFICIENT_SUPPORT'};return}const t=topology(links,cal.expectedCohort);if(!t.ok)return;const selected=t.links.map(l=>({...l,samples:l.samples.filter(s=>s.receive_wall_ms>=cal.started)}));const starts=selected.map(l=>l.samples[0]?.receive_wall_ms??Infinity),ends=selected.map(l=>l.samples.at(-1)?.receive_wall_ms??-Infinity);const overlap=Math.min(...ends)-Math.max(...starts);if(selected.some(l=>l.samples.length<DETECTOR_V5.calibrationMinSamplesPerLink)||overlap<DETECTOR_V5.calibrationMinOverlapMs)return;const session=nodes[0]?.session_id??'body-finder-lab';const calibrationId=`cal-d205-${cal.generation}-${coordinatorNodeId?.slice(-8)??'none'}-${cal.started}`;const out=native({operation:'BUILD_CALIBRATION',session_id:session,calibration_id:calibrationId,generation:cal.generation,topology_fingerprint:cal.topology,detector_parameter_hash:DETECTOR_PARAMETER_HASH,frozen_wall_ms:Date.now(),links:selected.map(l=>({...l,samples:l.samples.slice(-120)}))});if(out.calibration_state==='READY'&&out.artifact){cal={...cal,state:'READY',artifact:out.artifact,reason:'FROZEN_SYNCHRONIZED_EMPTY_CALIBRATION',lastAuthorityWallMs:Date.now()}}else{cal={...cal,state:'INVALID',artifact:null,reason:out.reason??'CALIBRATION_ENGINE_REJECTED'}}}
function membershipHealth(nodes:Advertisement[]){if(!cal.expectedCohort.length)return{confirmed:[] as string[]};const now=Date.now(),active=new Set(stableCohort(nodes)),missing=cal.expectedCohort.filter(id=>!active.has(id));for(const id of cal.expectedCohort){if(active.has(id))delete cal.missingSince[id];else if(!cal.missingSince[id])cal.missingSince[id]=now}return{confirmed:missing.filter(id=>now-(cal.missingSince[id]??now)>DETECTOR_V5.membershipChangeGraceMs)}}

export function estimateHumanPresence(nodes:Advertisement[],mode:'coordinator'|'diagnostic'='diagnostic',coordinatorNodeId:string|null=null,localNodeId:string|null=null):PresenceEstimate{const links=ingest(nodes);syncAuthoritativeCalibration(nodes,coordinatorNodeId,localNodeId);if(mode!=='coordinator')return fallback(cal.state==='STALE_AUTHORITY'?cal.reason:(cal.artifact?'authoritative_calibration_mirrored_awaiting_decision':'awaiting_elected_coordinator_publication'),cal.state);if(!coordinatorNodeId||coordinatorNodeId!==localNodeId)return fallback('not_elected_coordinator');maybeFreeze(nodes,coordinatorNodeId,localNodeId,links);if(cal.state!=='READY'||!cal.artifact)return fallback(cal.reason,cal.state);if(membershipHealth(nodes).confirmed.length){cal={...cal,state:'INVALID',reason:'CONFIRMED_SESSION_MEMBERSHIP_CHANGE_RECALIBRATION_REQUIRED'};return fallback(cal.reason,'INVALID')}const t=topology(links,cal.expectedCohort);if(!t.ok)return fallback('TRANSIENT_RF_OR_UDP_EVIDENCE_GAP_CALIBRATION_PRESERVED','READY');if(cal.artifact.detector_parameter_hash!==DETECTOR_PARAMETER_HASH){cal={...cal,state:'INVALID',artifact:null,reason:'DETECTOR_PARAMETER_HASH_CHANGED'};return fallback(cal.reason,'INVALID')}const start=Number(cal.artifact.frozen_wall_ms)+250;const obs=expectedLinks(links,cal.expectedCohort).map(l=>({...l,samples:l.samples.filter(s=>s.receive_wall_ms>=start).slice(-72)}));const now=Date.now();const input={operation:'INFER',session_id:nodes[0]?.session_id??'body-finder-lab',window_id:String(Math.floor(now/2000)*2000),window_start_wall_ms:Math.min(...obs.flatMap(l=>l.samples.map(s=>s.receive_wall_ms)),now),window_end_wall_ms:now,detector_parameter_hash:DETECTOR_PARAMETER_HASH,calibration:cal.artifact,acquisition_health:{environment_valid:true,acquisition_valid:true},links:obs};const out=native(input);if(out.error)return fallback(`canonical_engine_error:${out.error}`,'READY');const publication=getCalibrationPublication(localNodeId);return{...out,calibration_state:out.calibration_state??'READY',calibration_id:cal.artifact.calibration_id,calibration_hash:cal.artifact.calibration_hash,calibration_generation:cal.generation,coordinator_generation:cal.coordinatorGeneration,topology_fingerprint:cal.topology,expected_cohort:cal.expectedCohort,calibration_publication_v5:publication,authoritative:true,source:'canonical_shared_rust_engine'} as PresenceEstimate}
export function selectAuthoritativePresence(nodes:Advertisement[],coordinatorNodeId:string|null,localNodeId:string|null,local:PresenceEstimate):PresenceEstimate{syncAuthoritativeCalibration(nodes,coordinatorNodeId,localNodeId);if(!coordinatorNodeId)return fallback('coordinator_unavailable');if(coordinatorNodeId===localNodeId)return local;const coordinator=nodes.find(n=>n.node_id===coordinatorNodeId);const published=(coordinator?.published_geometry as any)?.authoritative_presence;if(published&&published.authoritative===true&&published.algorithm_version===DETECTOR_ALGORITHM&&published.parameter_hash===DETECTOR_PARAMETER_HASH&&published.canonical_digest){return{...published,calibration_state:cal.artifact?'READY':published.calibration_state,source:'elected_coordinator_publication'} as PresenceEstimate}return fallback(cal.state==='STALE_AUTHORITY'?cal.reason:'awaiting_authoritative_coordinator_publication',cal.state)}
