
import { Advertisement } from './autogeometry';
import BodyFinderNative from '../modules/body-finder-native';
import { DETECTOR_ALGORITHM, DETECTOR_PARAMETER_HASH, DETECTOR_V4 } from './detectorParameters';

export type PresencePrediction = 'HUMAN_EVIDENCE' | 'NO_HUMAN_EVIDENCE' | 'INDETERMINATE';
export type PresenceEstimate = {
  prediction: PresencePrediction; human_confidence: number; evidence_quality: string; fused_score: number;
  contributing_nodes: number; contributing_links: number; physical_baselines: number; reason: string;
  calibration_state: 'UNCALIBRATED'|'CALIBRATING'|'READY'|'INVALID'|'WAIT_COORDINATOR'; calibration_id?: string|null; calibration_hash?: string|null;
  algorithm_version: string; parameter_hash: string; window_id: string; decision_id?: string; canonical_digest?: string;
  authoritative: boolean; source: string; [key: string]: any;
};
type Sample={receive_wall_ms:number;source_monotonic_ns:number|null;rssi_dbm:number};
type Link={link_id:string;observer_node_id:string;peer_node_id:string;samples:Sample[]};
type CalState={state:PresenceEstimate['calibration_state'];generation:number;coordinator:string|null;topology:string|null;started:number;artifact:any|null;reason:string};
const HISTORY_MS=45_000; const history=new Map<string,Sample[]>(); const lastSource=new Map<string,number>();
let cal:CalState={state:'UNCALIBRATED',generation:0,coordinator:null,topology:null,started:0,artifact:null,reason:'EMPTY_CAL_REQUIRED'};

function fallback(reason:string,state:PresenceEstimate['calibration_state']=cal.state):PresenceEstimate{return{prediction:'INDETERMINATE',human_confidence:0.5,evidence_quality:'LOW',fused_score:0,contributing_nodes:0,contributing_links:0,physical_baselines:0,reason,calibration_state:state,calibration_id:cal.artifact?.calibration_id??null,calibration_hash:cal.artifact?.calibration_hash??null,algorithm_version:DETECTOR_ALGORITHM,parameter_hash:DETECTOR_PARAMETER_HASH,window_id:String(Math.floor(Date.now()/2000)*2000),authoritative:false,source:'diagnostic_fail_closed'}}
function pair(a:string,b:string){return a<b?`${a}::${b}`:`${b}::${a}`}
function ingest(nodes:Advertisement[]):Link[]{const now=Date.now();for(const n of nodes){for(const r of n.ranges??[]){const v=Number(r.rssi_dbm);if(!Number.isFinite(v)||v>0||v<-126)continue;const observer=String(r.observer_node_id||n.node_id||'');const peer=String(r.peer_node_id||'');if(!observer||!peer)continue;const id=`${observer}::${peer}`;const source=Number((r as any).source_observation_monotonic_ns??r.monotonic_ns??0);if(source>0&&lastSource.get(id)===source)continue;if(source>0)lastSource.set(id,source);const q=history.get(id)??[];q.push({receive_wall_ms:now,source_monotonic_ns:source>0?source:null,rssi_dbm:v});history.set(id,q.filter(s=>now-s.receive_wall_ms<=HISTORY_MS).slice(-160));}}
return [...history.entries()].map(([id,samples])=>{const [observer,peer]=id.split('::');return{link_id:id,observer_node_id:observer,peer_node_id:peer,samples}}).sort((a,b)=>a.link_id.localeCompare(b.link_id))}
function topology(links:Link[]){const live=links.filter(l=>l.samples.length&&Date.now()-l.samples.at(-1)!.receive_wall_ms<6000);const nodes=new Set(live.map(l=>l.observer_node_id));const baselines=new Set(live.map(l=>pair(l.observer_node_id,l.peer_node_id)));return{ok:nodes.size>=3&&live.length>=6&&baselines.size>=3,fingerprint:[...nodes].sort().join(',')+'|'+live.map(l=>l.link_id).sort().join(','),links:live,nodes:nodes.size,baselines:baselines.size}}
function native(input:any){try{const out=JSON.parse(BodyFinderNative.evaluateHumanPresenceJson(JSON.stringify(input)));if(out?.error)throw new Error(String(out.error));return out}catch(e:any){return{error:String(e?.message??e)}}}

export function beginSessionPresenceCalibration(nodes:Advertisement[],coordinatorNodeId:string|null,localNodeId:string|null){const links=ingest(nodes);const t=topology(links);if(!coordinatorNodeId||coordinatorNodeId!==localNodeId){cal={...cal,state:'WAIT_COORDINATOR',coordinator:coordinatorNodeId,reason:'CALIBRATION_MUST_BE_STARTED_ON_ELECTED_COORDINATOR'};return cal}if(!t.ok){cal={...cal,state:'INVALID',coordinator:coordinatorNodeId,reason:'CALIBRATION_REQUIRES_3_NODES_6_LINKS_3_BASELINES'};return cal}cal={state:'CALIBRATING',generation:cal.generation+1,coordinator:coordinatorNodeId,topology:t.fingerprint,started:Date.now(),artifact:null,reason:'COLLECTING_SYNCHRONIZED_EMPTY_BASELINE'};return cal}
export function getSessionPresenceCalibration(){return{state:cal.state,generation:cal.generation,coordinator_node_id:cal.coordinator,topology_fingerprint:cal.topology,started_wall_ms:cal.started,calibration_id:cal.artifact?.calibration_id??null,calibration_hash:cal.artifact?.calibration_hash??null,reason:cal.reason}}

function maybeFreeze(nodes:Advertisement[],coordinatorNodeId:string|null,localNodeId:string|null,links:Link[]){if(cal.state!=='CALIBRATING'||coordinatorNodeId!==localNodeId)return;const t=topology(links);if(!t.ok||t.fingerprint!==cal.topology){cal={...cal,state:'INVALID',artifact:null,reason:'TOPOLOGY_CHANGED_DURING_CALIBRATION'};return}const selected=t.links.map(l=>({...l,samples:l.samples.filter(s=>s.receive_wall_ms>=cal.started)}));if(Date.now()-cal.started<7000||selected.some(l=>l.samples.length<DETECTOR_V4.minSamplesPerLink))return;const session=nodes[0]?.session_id??'body-finder-lab';const calibrationId=`cal-d204-${cal.generation}-${coordinatorNodeId?.slice(-8)??'none'}-${cal.started}`;const out=native({operation:'BUILD_CALIBRATION',session_id:session,calibration_id:calibrationId,generation:cal.generation,topology_fingerprint:t.fingerprint,detector_parameter_hash:DETECTOR_PARAMETER_HASH,frozen_wall_ms:Date.now(),links:selected.map(l=>({...l,samples:l.samples.slice(-80)}))});if(out.calibration_state==='READY'&&out.artifact){cal={...cal,state:'READY',artifact:out.artifact,reason:'FROZEN_SYNCHRONIZED_EMPTY_CALIBRATION'}}else{cal={...cal,state:'INVALID',artifact:null,reason:out.reason??'CALIBRATION_ENGINE_REJECTED'}}}

export function estimateHumanPresence(nodes:Advertisement[],mode:'coordinator'|'diagnostic'='diagnostic',coordinatorNodeId:string|null=null,localNodeId:string|null=null):PresenceEstimate{const links=ingest(nodes);if(mode!=='coordinator')return fallback('awaiting_elected_coordinator_publication');if(!coordinatorNodeId||coordinatorNodeId!==localNodeId)return fallback('not_elected_coordinator');maybeFreeze(nodes,coordinatorNodeId,localNodeId,links);if(cal.state!=='READY'||!cal.artifact)return fallback(cal.reason,cal.state);const t=topology(links);if(!t.ok||t.fingerprint!==cal.topology){cal={...cal,state:'INVALID',artifact:null,reason:'TOPOLOGY_CHANGED_AFTER_CALIBRATION'};return fallback(cal.reason,'INVALID')}if(cal.artifact.detector_parameter_hash!==DETECTOR_PARAMETER_HASH){cal={...cal,state:'INVALID',artifact:null,reason:'DETECTOR_PARAMETER_HASH_CHANGED'};return fallback(cal.reason,'INVALID')}
const start=Number(cal.artifact.frozen_wall_ms)+250;const obs=t.links.map(l=>({...l,samples:l.samples.filter(s=>s.receive_wall_ms>=start).slice(-48)}));const now=Date.now();const input={operation:'INFER',session_id:nodes[0]?.session_id??'body-finder-lab',window_id:String(Math.floor(now/2000)*2000),window_start_wall_ms:Math.min(...obs.flatMap(l=>l.samples.map(s=>s.receive_wall_ms)),now),window_end_wall_ms:now,detector_parameter_hash:DETECTOR_PARAMETER_HASH,calibration:cal.artifact,acquisition_health:{environment_valid:true,acquisition_valid:true},links:obs};const out=native(input);if(out.error)return fallback(`canonical_engine_error:${out.error}`,'INVALID');return{...out,calibration_state:out.calibration_state??'READY',calibration_id:cal.artifact.calibration_id,calibration_hash:cal.artifact.calibration_hash,authoritative:true,source:'canonical_shared_rust_engine'} as PresenceEstimate}

export function selectAuthoritativePresence(nodes:Advertisement[],coordinatorNodeId:string|null,localNodeId:string|null,local:PresenceEstimate):PresenceEstimate{if(!coordinatorNodeId)return fallback('coordinator_unavailable');if(coordinatorNodeId===localNodeId)return local;const coordinator=nodes.find(n=>n.node_id===coordinatorNodeId);const published=(coordinator?.published_geometry as any)?.authoritative_presence;if(published&&published.authoritative===true&&published.algorithm_version===DETECTOR_ALGORITHM&&published.parameter_hash===DETECTOR_PARAMETER_HASH&&published.canonical_digest){return{...published,source:'elected_coordinator_publication'} as PresenceEstimate}return fallback('awaiting_authoritative_coordinator_publication')}
