import { requireNativeModule } from 'expo-modules-core';

export type NativeApi = {
  getCapabilitiesJson(): string; getDiagnosticsJson(): string; exportPreRunDiagnosticJson(contextJson: string): string; shareJsonFile(json: string, filename: string): boolean;
  evaluateHumanPresenceJson(inputJson: string): string; sha256Text(text: string): string;
  getWifiRssi(): number | null; updateLocalState(baseline: number | null, sigma: number | null, scanning: boolean): boolean;
  updateControlPlaneJson(controlPlaneJson: string | null): boolean;
  updatePublishedGeometry(publish: boolean, geometryJson: string | null): boolean; updateGeometryState(geometryState: string): boolean;
  updateValidationTruthJson(truthJson: string): boolean; updateAppVisibility(visibility: string): boolean; startValidationRun(scenario: string): string; startDistributedValidationRun(scenario: string, contextJson: string): string;
  endValidationRun(): boolean; commitDistributedFreezeAndEnd(commitJson: string): boolean; getValidationRunJson(): string; getCompletedValidationRunsSummaryJson(): string;
  selectValidationRun(runId: string): boolean; getCalibrationSnapshotJson(): string;
  startFabric(nodeId: string | null, displayName: string | null, sessionId: string | null): Promise<boolean>; stopFabric(): boolean;
  getPeersJson(): string; getLocalAdvertisementJson(): string;
};
const native = requireNativeModule<NativeApi>('BodyFinderNative');
const ACCEPTANCE_MINIMUM_MS=330_000;
const EVIDENCE_SCHEMA='dev20.13-self-contained-json-evidence-v16';
function sanitizeCalibrationSnapshotJson(raw:string):string{try{const value=JSON.parse(raw);const walk=(node:any):any=>{if(Array.isArray(node))return node.map(walk);if(!node||typeof node!=='object')return node;const out:any={};for(const [key,child] of Object.entries(node)){if(key==='rssi_samples_dbm'&&Array.isArray(child))out[key]=child.filter(sample=>typeof sample==='number'&&Number.isFinite(sample)&&sample!==127&&sample>=-127&&sample<=20);else out[key]=walk(child);}return out;};return JSON.stringify(walk(value));}catch{return raw;}}
function upgradeValidationContract(raw:string):string{try{const d=JSON.parse(raw);const v=d?.validation_run??d;if(v&&typeof v==='object'){const elapsed=Number(v.elapsed_ms??v.snapshot_elapsed_ms??0);v.acceptance_minimum_ms=ACCEPTANCE_MINIMUM_MS;v.acceptance_duration_eligible=elapsed>=ACCEPTANCE_MINIMUM_MS;v.short_diagnostic_run=elapsed>0&&elapsed<ACCEPTANCE_MINIMUM_MS;v.evidence_contract_version=EVIDENCE_SCHEMA;}if(Array.isArray(d?.completed_validation_runs_summary))for(const v of d.completed_validation_runs_summary){const elapsed=Number(v?.elapsed_ms??0);v.acceptance_minimum_ms=ACCEPTANCE_MINIMUM_MS;v.acceptance_duration_eligible=elapsed>=ACCEPTANCE_MINIMUM_MS;v.short_diagnostic_run=elapsed>0&&elapsed<ACCEPTANCE_MINIMUM_MS;}return JSON.stringify(d);}catch{return raw;}}
function upgradeExport(raw:string):string{try{const d=JSON.parse(raw),v=d?.validation_run??d,truth=v?.validation_truth??d?.validation_truth??{},start=truth?.distributed_start??null,freeze=truth?.freeze_barrier??null,preview=truth?.authoritative_presence??d?.human_presence_preview??null;const reasons:string[]=[];if(start?.committed!==true||Number(start?.ready_count??0)!==3)reasons.push('DISTRIBUTED_START_NOT_COMMITTED_3_OF_3');if(freeze?.committed!==true||Number(freeze?.ready_count??0)!==3||freeze?.ready_parity!==true)reasons.push('DISTRIBUTED_FREEZE_NOT_COMMITTED_3_OF_3');if(v?.distributed_freeze_committed!==true)reasons.push('NATIVE_DISTRIBUTED_FREEZE_NOT_COMMITTED');if(!v?.campaign_run_token)reasons.push('CAMPAIGN_RUN_TOKEN_MISSING');if(!preview?.authoritative)reasons.push('NO_FROZEN_AUTHORITATIVE_DECISION');if(!preview?.canonical_digest)reasons.push('MISSING_CANONICAL_DIGEST');if(!preview?.decision_id)reasons.push('MISSING_DECISION_ID');if(Number(preview?.contributing_nodes??0)<3||Number(preview?.contributing_links??0)<6||Number(preview?.physical_baselines??0)<3)reasons.push('INCOMPLETE_3_6_3_TOPOLOGY');const valid=reasons.length===0;d.live_human_presence_preview=d?.human_presence_preview??null;d.human_presence_preview=preview;d.evidence_export_valid=valid;d.atomic_snapshot_gate_pass=valid;d.evidence_invalid_reasons=reasons;d.evidence_contract={schema:EVIDENCE_SCHEMA,screenshots_required:false,json_self_contained:true,atomic_snapshot:true,distributed_commit_required:true};d.acceptance_minimum_ms=ACCEPTANCE_MINIMUM_MS;d.human_localization_validated=false;d.rescue_use_validated=false;if(v&&typeof v==='object'){v.evidence_export_valid=valid;v.atomic_snapshot_gate_pass=valid;v.evidence_contract_version=EVIDENCE_SCHEMA;}return JSON.stringify(d,null,2)}catch{return raw}}
const api:NativeApi={...native,getDiagnosticsJson:()=>upgradeValidationContract(native.getDiagnosticsJson()),getValidationRunJson:()=>upgradeValidationContract(native.getValidationRunJson()),getCompletedValidationRunsSummaryJson:()=>upgradeValidationContract(native.getCompletedValidationRunsSummaryJson()),getCalibrationSnapshotJson:()=>sanitizeCalibrationSnapshotJson(native.getCalibrationSnapshotJson()),shareJsonFile:(json,filename)=>native.shareJsonFile(upgradeExport(json),filename)};
export default api;
