import { requireNativeModule } from 'expo-modules-core';

export type NativeApi = {
  getCapabilitiesJson(): string; getDiagnosticsJson(): string; shareJsonFile(json: string, filename: string): boolean;
  evaluateHumanPresenceJson(inputJson: string): string;
  getWifiRssi(): number | null; updateLocalState(baseline: number | null, sigma: number | null, scanning: boolean): boolean;
  updateControlPlaneJson(controlPlaneJson: string | null): boolean;
  updatePublishedGeometry(publish: boolean, geometryJson: string | null): boolean; updateGeometryState(geometryState: string): boolean;
  updateValidationTruthJson(truthJson: string): boolean; updateAppVisibility(visibility: string): boolean; startValidationRun(scenario: string): string;
  endValidationRun(): boolean; getValidationRunJson(): string; getCompletedValidationRunsSummaryJson(): string;
  selectValidationRun(runId: string): boolean; getCalibrationSnapshotJson(): string;
  startFabric(nodeId: string | null, displayName: string | null, sessionId: string | null): Promise<boolean>; stopFabric(): boolean;
  getPeersJson(): string; getLocalAdvertisementJson(): string;
};
const native = requireNativeModule<NativeApi>('BodyFinderNative');
const ACCEPTANCE_MINIMUM_MS=330_000;
const EVIDENCE_SCHEMA='dev20.8-self-contained-json-evidence-v11';
function sanitizeCalibrationSnapshotJson(raw:string):string{try{const value=JSON.parse(raw);const walk=(node:any):any=>{if(Array.isArray(node))return node.map(walk);if(!node||typeof node!=='object')return node;const out:any={};for(const [key,child] of Object.entries(node)){if(key==='rssi_samples_dbm'&&Array.isArray(child))out[key]=child.filter(sample=>typeof sample==='number'&&Number.isFinite(sample)&&sample!==127&&sample>=-127&&sample<=20);else out[key]=walk(child);}return out;};return JSON.stringify(walk(value));}catch{return raw;}}
function upgradeValidationContract(raw:string):string{try{const d=JSON.parse(raw);const v=d?.validation_run??d;if(v&&typeof v==='object'){const elapsed=Number(v.elapsed_ms??v.snapshot_elapsed_ms??0);v.acceptance_minimum_ms=ACCEPTANCE_MINIMUM_MS;v.acceptance_duration_eligible=elapsed>=ACCEPTANCE_MINIMUM_MS;v.short_diagnostic_run=elapsed>0&&elapsed<ACCEPTANCE_MINIMUM_MS;v.evidence_contract_version=EVIDENCE_SCHEMA;}if(Array.isArray(d?.completed_validation_runs_summary))for(const v of d.completed_validation_runs_summary){const elapsed=Number(v?.elapsed_ms??0);v.acceptance_minimum_ms=ACCEPTANCE_MINIMUM_MS;v.acceptance_duration_eligible=elapsed>=ACCEPTANCE_MINIMUM_MS;v.short_diagnostic_run=elapsed>0&&elapsed<ACCEPTANCE_MINIMUM_MS;}return JSON.stringify(d);}catch{return raw;}}
function upgradeExport(raw:string):string{try{const d=JSON.parse(raw);const livePreview=d?.human_presence_preview??null;const frozen=d?.validation_run?.validation_truth?.authoritative_presence??d?.validation_truth?.authoritative_presence??null;const preview=frozen?.authoritative===true?frozen:livePreview;const digest=preview?.canonical_digest??null;const reasons:string[]=[];if(!preview?.authoritative)reasons.push('NO_FROZEN_AUTHORITATIVE_DECISION');if(!digest)reasons.push('MISSING_CANONICAL_DIGEST');if(!preview?.decision_id)reasons.push('MISSING_DECISION_ID');if(!preview?.canonical_replay_input)reasons.push('MISSING_CANONICAL_REPLAY');if(Number(preview?.contributing_nodes??0)<3||Number(preview?.contributing_links??0)<6||Number(preview?.physical_baselines??0)<3)reasons.push('INCOMPLETE_3_6_3_TOPOLOGY');const evidenceValid=reasons.length===0;d.live_human_presence_preview=livePreview;d.human_presence_preview=preview;d.evidence_export_valid=evidenceValid;d.evidence_invalid_reasons=reasons;d.atomic_snapshot_gate_pass=evidenceValid;d.evidence_contract={...(d.evidence_contract??{}),schema:EVIDENCE_SCHEMA,screenshots_required:false,json_self_contained:true,required_external_input:'ground_truth_and_scenario_metadata_only_for_final_validator',diagnostic_source:'this JSON export',atomic_snapshot:true};d.acceptance_minimum_ms=ACCEPTANCE_MINIMUM_MS;d.human_localization_validated=false;d.rescue_use_validated=false;d.snapshot_consistency_digest=digest;d.snapshot_consistency_source=digest?'frozen_validation_run.authoritative_presence.canonical_digest':'NO_AUTHORITATIVE_DECISION_AT_SNAPSHOT';if(d.validation_run){const elapsed=Number(d.validation_run.elapsed_ms??0);d.validation_run.acceptance_minimum_ms=ACCEPTANCE_MINIMUM_MS;d.validation_run.acceptance_duration_eligible=elapsed>=ACCEPTANCE_MINIMUM_MS;d.validation_run.short_diagnostic_run=elapsed>0&&elapsed<ACCEPTANCE_MINIMUM_MS;d.validation_run.evidence_contract_version=EVIDENCE_SCHEMA;}return JSON.stringify(d,null,2);}catch{return raw;}}
const api:NativeApi={...native,getDiagnosticsJson:()=>upgradeValidationContract(native.getDiagnosticsJson()),getValidationRunJson:()=>upgradeValidationContract(native.getValidationRunJson()),getCompletedValidationRunsSummaryJson:()=>upgradeValidationContract(native.getCompletedValidationRunsSummaryJson()),getCalibrationSnapshotJson:()=>sanitizeCalibrationSnapshotJson(native.getCalibrationSnapshotJson()),shareJsonFile:(json,filename)=>native.shareJsonFile(upgradeExport(json),filename)};
export default api;
