#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
MODULE=ROOT/'apps/mobile/modules/body-finder-native/android/src/main/java/com/trochez/bodyfindernative/BodyFinderNativeModule.kt'; ACQ=ROOT/'apps/mobile/modules/body-finder-native/android/src/main/java/com/trochez/bodyfindernative/BleAcquisitionPolicy.kt'; CONT=ROOT/'apps/mobile/modules/body-finder-native/android/src/main/java/com/trochez/bodyfindernative/BleContinuityPolicy.kt'; SYSTEM=ROOT/'apps/mobile/modules/body-finder-native/android/src/main/java/com/trochez/bodyfindernative/SystemRangingApi36.kt'; ESTIMATOR=ROOT/'apps/mobile/modules/body-finder-native/android/src/main/java/com/trochez/bodyfindernative/BleRangeEstimator.kt'; APP=ROOT/'apps/mobile/App.tsx'; VERSION=ROOT/'apps/mobile/src/version.ts'; APP_JSON=ROOT/'apps/mobile/app.json'; PROFILES=ROOT/'calibration/ble-range-calibration-profiles.json'
def require(c,m):
    if not c: raise SystemExit('BLE ACQUISITION CONTRACT FAILED: '+m)
def close(a,b,t=1e-6): return abs(a-b)<=t
module=MODULE.read_text(); acq=ACQ.read_text(); cont=CONT.read_text(); system=SYSTEM.read_text(); estimator=ESTIMATOR.read_text(); app=APP.read_text(); version=VERSION.read_text(); app_json=json.loads(APP_JSON.read_text()); profiles=json.loads(PROFILES.read_text()); active=next(p for p in profiles['profiles'] if p['profile_id']==profiles['active_profile_id'])
require(active['profile_id']=='android-ble-lab-v1' and active['validated'] and active['physical_confidence']=='COARSE','profile truth changed'); require(close(float(active['rssi_at_1m_dbm']),-69.19) and close(float(active['path_loss_exponent']),3.62),'BLE calibration changed'); require(close(float(active['valid_distance_min_m']),0.5) and close(float(active['valid_distance_max_m']),5.0),'metric domain changed')
require('private const val MIN_SAMPLES_FOR_RANGE = 3' in module and 'private const val RANGE_FRESHNESS_MS = 5_000L' in module,'range sample/freshness truth changed'); require('HOLDOVER_MAX_MS = 10_000L' in cont and 'HARD_EXPIRY_MS = 10_000L' in cont and 'SIGMA_AGING_M_PER_S = 0.15' in cont,'temporal truth changed'); require('coerceIn(0.5, 5.0)' not in module+estimator,'silent metric clamp reintroduced')
for t in ['FILTERED_PRIMARY','UNFILTERED_RECOVERY','FILTERED_RECOVERY_PROBE','COOLDOWN','FAILED_SAFE','ScanSettings.SCAN_MODE_LOW_LATENCY','setReportDelay(REPORT_DELAY_MS)','ScanSettings.CALLBACK_TYPE_ALL_MATCHES','ScanSettings.MATCH_MODE_AGGRESSIVE','ScanSettings.MATCH_NUM_MAX_ADVERTISEMENT','startFilteredScan','startUnfilteredRecoveryScan','manufacturerFilter','COHORT_STALL_THRESHOLD_MS = 5_000L','RECOVERY_UNFILTERED_WINDOW_MS = 10_000L','FILTERED_PROBE_WINDOW_MS = 15_000L','MIN_RESTART_COOLDOWN_MS = 30_000L','MAX_RECOVERY_ATTEMPTS_PER_5MIN = 3','recoveryGenerationCounter','activeRecoveryGeneration']:
    require(t in acq,'adaptive acquisition token missing: '+t)
require('BleAcquisitionPolicy.startFilteredScan' in module and 'BleAcquisitionPolicy.startUnfilteredRecoveryScan' in module,'scanner strategy paths missing'); require('getManufacturerSpecificData(MANUFACTURER_ID)' in module and 'payloadIdentity(raw)' in module,'Body Finder payload validation missing'); require('ADVERTISE_TX_POWER_MEDIUM' in module,'advertise Tx power changed')
for t in ['GLOBAL_SCANNER_HEALTHY','GLOBAL_SCANNER_STALLED','BF_COHORT_HEALTHY','BF_COHORT_SPARSE','BF_COHORT_STALLED','BF_COHORT_RECOVERING','maintainAdaptiveScanner','bodyFinderCohortHealth','strategy_transition_count','cohort_stall_count','cohort_recovery_count','cohort_recovery_failure_count','restart_suppressed_by_cooldown_count','recovery_attempt_count','filtered_mode_total_ms','unfiltered_recovery_total_ms']:
    require(t in acq+module,'cohort recovery token missing: '+t)
for t in ['BleAcquisitionStats','acquisitionStatsByIdentity','callback_rate_hz','valid_callback_rate_hz','mean_interarrival_ms','max_interarrival_ms','p50_interarrival_ms','p95_interarrival_ms','gap_gt_1s_count','gap_gt_2s_count','gap_gt_5s_count','gap_gt_10s_count','peer_stall_count','peer_recovery_count','run_recovery_participation_count','run_first_callback_after_recovery_count','acquisition_health']:
    require(t in acq+module,'acquisition telemetry missing: '+t)
require('VALIDATION_ENVIRONMENT_INVALID' in module and 'BATTERY_SAVER_ON' in module,'Battery Saver validation gate missing'); require('SYSTEM_RANGING_BLE_YIELD_MS = 120_000L' in acq and 'SYSTEM_RANGING_CLOSES_BEFORE_YIELD = 6L' in acq,'BLE yield policy changed')
for t in ['BLE_ACQUISITION_YIELD','ble_yield_active','ble_yield_reason','closes_since_real_result','isBleYieldActive','counterSnapshot','RANGING_YIELD_ENTER']:
    require(t in system+module,'RangingManager correlation/yield token missing: '+t)
on_opened=system[system.find('override fun onOpened()'):system.find('override fun onOpenFailed')]; require('registerRealRangeSuccess' not in on_opened,'onOpened incorrectly resets failure state'); require('if (distanceM != null) registerRealRangeSuccess(received)' in system,'real distance is not success gate')
for t in ['CompletedValidationRun','MAX_COMPLETED_VALIDATION_RUNS = 5','snapshot_frozen','snapshot_schema_version','recovery_attempt_delta','restart_suppressed_delta','ranging_yield_transition_delta','acquisition_state_at_end','event_timeline_total_count','selectedCompletedRunId']:
    require(t in module,'dev11 validation-integrity token missing: '+t)
require('0.2.0-experimental.11' in version and 'reportVersion: 13' in version,'mobile/report version incorrect'); require('humanScanningEnabled: false' in version,'human scanning must remain blocked'); require(app_json['expo']['android']['versionCode']==11 and app_json['expo']['extra']['releaseIteration']=='experimental.11','release metadata incorrect')
print(json.dumps({'contract':'experimental.11 adaptive BLE acquisition + immutable validation integrity','profile_frozen':True,'min_samples':3,'fresh_ms':5000,'holdover_max_ms':10000,'primary_strategy':'FILTERED_PRIMARY','recovery_strategy':'UNFILTERED_RECOVERY','cohort_stall_ms':5000,'restart_cooldown_ms':30000,'max_recovery_attempts_per_5min':3,'ranging_manager_ble_yield_ms':120000,'human_scanning_enabled':False},indent=2))
