#!/usr/bin/env python3
from pathlib import Path
import re,json
R=Path(__file__).resolve().parents[1]
def rd(x):return (R/x).read_text()
def wr(x,s):p=R/x;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(s)
def rep(s,a,b,n='anchor'):
 if a not in s:
  if b in s:return s
  raise SystemExit('missing '+n)
 return s.replace(a,b,1)
BUILD='0.2.0-experimental.20.10';PARAM='f5795d40fbfb1de728b8576e214b249ada67f70d7962e1bf7794eb9c7d251f17'
# release identity
s=rd('apps/mobile/src/version.ts').replace('0.2.0-experimental.20.9',BUILD).replace('reportVersion: 29','reportVersion: 30').replace('versionCode: 29','versionCode: 30').replace('experimental.20.9','experimental.20.10').replace('snapshotSchemaVersion: 12','snapshotSchemaVersion: 13');wr('apps/mobile/src/version.ts',s)
for x in ['apps/mobile/android/app/build.gradle','apps/mobile/android-legacy/app/build.gradle']:
 if (R/x).exists():
  s=rd(x);s=re.sub(r'versionCode\s+29\b','versionCode 30',s).replace('0.2.0-experimental.20.9',BUILD);wr(x,s)
# App: scenario exported only from frozen run, contract identity fixed
s=rd('apps/mobile/App.tsx')
s=s.replace('scenario: selectedRun?.scenario ?? validationScenario,','scenario: selectedRun?.scenario ?? null,')
s=s.replace("schema: 'dev20.8-self-contained-json-evidence-v11'","schema: 'dev20.10-self-contained-json-evidence-v13'")
s=s.replace("schema:'dev20.5-diagnostic-contract-v8'","schema:'dev20.10-diagnostic-contract-v13'")
# live UI may select next scenario but native run owns immutable scenario
s=s.replace('scenario: validationScenario,\n    human_presence_calibration_status','scenario: validationRun?.active ? (validationRun?.scenario ?? validationScenario) : validationScenario,\n    human_presence_calibration_status')
s=s.replace('fused.diagnostics, validationScenario]);','fused.diagnostics, validationScenario, validationRun?.active, validationRun?.scenario]);')
wr('apps/mobile/App.tsx',s)
# TS native evidence identity
s=rd('apps/mobile/modules/body-finder-native/index.ts').replace('dev20.9-self-contained-json-evidence-v12','dev20.10-self-contained-json-evidence-v13').replace('dev20.8-self-contained-json-evidence-v11','dev20.10-self-contained-json-evidence-v13').replace('dev20.5-diagnostic-contract-v8','dev20.10-diagnostic-contract-v13');wr('apps/mobile/modules/body-finder-native/index.ts',s)
# detector v9: no global threshold change; coherent low-amplitude signal must span >=2 baselines
x='crates/body-finder-science/src/human_detector.rs';s=rd(x).replace('deterministic-multinode-rssi-fusion-v8','deterministic-multinode-rssi-fusion-v9').replace('5d404d404e08d33cd179aa8657edd93f1e51885f5dfa1268af228465642a8d39',PARAM).replace('"d208-{}"','"d210-{}"').replace('publication_contract_version: 8','publication_contract_version: 9')
s=rep(s,'    let coherent_low_amplitude_motion =\n        fused >= 0.26 && base >= 0.20 && recip >= 0.70 && cross >= (1.0 / 6.0) && bs >= (1.0 / 3.0);','    let coherent_low_amplitude_motion = fused >= 0.26\n        && base >= 0.20\n        && recip >= 0.70\n        && cross >= (1.0 / 6.0)\n        && bs >= (1.0 / 3.0)\n        && transition_phys.len() >= 2;','detector gate')
wr(x,s)
if (R/'apps/mobile/src/detectorParameters.ts').exists():
 s=rd('apps/mobile/src/detectorParameters.ts').replace('deterministic-multinode-rssi-fusion-v8','deterministic-multinode-rssi-fusion-v9').replace('5d404d404e08d33cd179aa8657edd93f1e51885f5dfa1268af228465642a8d39',PARAM);wr('apps/mobile/src/detectorParameters.ts',s)
# native runtime
x='apps/mobile/modules/body-finder-native/android/src/main/java/com/trochez/bodyfindernative/BodyFinderNativeModule.kt';s=rd(x)
s=s.replace('WireTransportV9','WireTransportV10').replace('WireEnvelopeV9','WireEnvelopeV10').replace('WireTransportTelemetryV9','WireTransportTelemetryV10').replace('wire_transport_v8','wire_transport_v10').replace('GeometryPublicationV9','GeometryPublicationV10').replace('snapshot_schema_version", 11','snapshot_schema_version", 13').replace('dev16-self-contained-json-evidence-v4','dev20.10-self-contained-json-evidence-v13')
s=rep(s,'  @Volatile private var validationTruthJson: String = "{}"\n  @Volatile private var authoritativeTruthLedgerJson: String = "{}"','  @Volatile private var validationTruthJson: String = "{}"\n  @Volatile private var authoritativeTruthLedgerJson: String = "{}"\n  @Volatile private var scenarioGeneration: Long = 0\n  @Volatile private var scenarioStartedWallMs: Long = 0','scenario fields')
s=rep(s,'  fun start(now: Long, peerExpire: Long, rebind: Long, scanRestart: Long, tx: Long, rx: Long, preflightJson: String): String {\n    if (runId != null && endedWallMs == null) return runId!!\n    val id = UUID.randomUUID().toString()','  fun start(now: Long, peerExpire: Long, rebind: Long, scanRestart: Long, tx: Long, rx: Long, preflightJson: String, scenarioId: String): String {\n    if (runId != null && endedWallMs == null) return runId!!\n    require(scenarioId.isNotBlank() && scenarioId != "UNSPECIFIED") { "SCENARIO_UNSPECIFIED" }\n    val id = UUID.randomUUID().toString()\n    scenario = scenarioId\n    scenarioGeneration += 1\n    scenarioStartedWallMs = now','start scenario')
s=rep(s,'    val incoming = try { JSONObject(json) } catch (_: Throwable) { JSONObject() }\n    validationTruthJson = incoming.toString()','    val incoming = try { JSONObject(json) } catch (_: Throwable) { JSONObject() }\n    incoming.put("scenario", scenario).put("scenario_generation", scenarioGeneration).put("scenario_started_wall_ms", scenarioStartedWallMs)\n    validationTruthJson = incoming.toString()','truth scenario')
s=s.replace('.put("scenario", scenario)\n      .put("started_wall_ms", start ?: JSONObject.NULL)','.put("scenario", scenario)\n      .put("scenario_generation", scenarioGeneration)\n      .put("scenario_started_wall_ms", scenarioStartedWallMs)\n      .put("started_wall_ms", start ?: JSONObject.NULL)')
s=rep(s,'    base.put("evidence_export_valid", evidenceValid)\n      .put("evidence_invalid_reasons", invalidReasons)','    val scenarioMaterial="$id|$scenario|$scenarioGeneration|${startedWallMs ?: 0L}|$now"\n    val scenarioDigest="sha256:"+MessageDigest.getInstance("SHA-256").digest(scenarioMaterial.toByteArray(Charsets.UTF_8)).joinToString(""){"%02x".format(it)}\n    base.put("scenario",scenario).put("scenario_generation",scenarioGeneration).put("scenario_started_wall_ms",scenarioStartedWallMs).put("scenario_consistency_digest",scenarioDigest)\n    base.put("evidence_export_valid", evidenceValid)\n      .put("evidence_invalid_reasons", invalidReasons)','scenario digest')
s=s.replace('.put("run_id", run.runId)\n        .put("started_wall_ms"','.put("run_id", run.runId)\n        .put("scenario", j.optString("scenario"))\n        .put("scenario_generation", j.optLong("scenario_generation"))\n        .put("scenario_consistency_digest", j.opt("scenario_consistency_digest"))\n        .put("started_wall_ms"')
# V10 MTU/backpressure
s=s.replace('const val RANGE_FRAME_TARGET_BYTES = 1050','const val RANGE_FRAME_TARGET_BYTES = 1050\n  const val CONTROL_FRAME_TARGET_BYTES = 900')
s=s.replace('private const val NACK_INTERVAL_MS = 500L','private const val NACK_INTERVAL_MS = 1_000L').replace('private const val FULL_RETRY_MS = 3_000L','private const val FULL_RETRY_MS = 3_000L\n  private const val MAX_RETRY_BACKOFF_MS = 12_000L\n  private const val ARTIFACT_WINDOW_CHUNKS = 4')
s=rep(s,'    val chunks:List<ByteArray>,var seq:Long,var lastFullSendWallMs:Long=0L,\n    val ackPeers:MutableSet<String> = java.util.concurrent.ConcurrentHashMap.newKeySet()','    val chunks:List<ByteArray>,var seq:Long,var lastFullSendWallMs:Long=0L,var nextChunkIndex:Int=0,var retryBackoffMs:Long=FULL_RETRY_MS,var lastNackSignature:String="",var lastNackWallMs:Long=0L,\n    val ackPeers:MutableSet<String> = java.util.concurrent.ConcurrentHashMap.newKeySet()','outbound fields')
s=rep(s,'  private val maxBytesByType=java.util.concurrent.ConcurrentHashMap<String,java.util.concurrent.atomic.AtomicLong>()\n  val requiredFrameOversizeCount=java.util.concurrent.atomic.AtomicLong(0)','  private val maxBytesByType=java.util.concurrent.ConcurrentHashMap<String,java.util.concurrent.atomic.AtomicLong>()\n  private val oversizeDropByType=java.util.concurrent.ConcurrentHashMap<String,java.util.concurrent.atomic.AtomicLong>()\n  val requiredFrameOversizeCount=java.util.concurrent.atomic.AtomicLong(0)','oversize map')
s=rep(s,'    if(type=="RANGE_FRAME" && b.size>RANGE_FRAME_TARGET_BYTES){requiredFrameOversizeCount.incrementAndGet();oversizeBlockCount.incrementAndGet();throw IllegalStateException("WIRE_OVERSIZE_RANGE_FRAME_${b.size}")}\n    if(b.size>MAX_DATAGRAM_BYTES){if(type=="RANGE_FRAME")requiredFrameOversizeCount.incrementAndGet();oversizeBlockCount.incrementAndGet();throw IllegalStateException("WIRE_OVERSIZE_${type}_${b.size}")}','    if(type=="RANGE_FRAME" && b.size>RANGE_FRAME_TARGET_BYTES){requiredFrameOversizeCount.incrementAndGet();oversizeBlockCount.incrementAndGet();oversizeDropByType.computeIfAbsent(type){java.util.concurrent.atomic.AtomicLong(0)}.incrementAndGet();throw IllegalStateException("WIRE_OVERSIZE_RANGE_FRAME_${b.size}")}\n    if(type=="CONTROL_FRAME" && b.size>CONTROL_FRAME_TARGET_BYTES){requiredFrameOversizeCount.incrementAndGet();oversizeBlockCount.incrementAndGet();oversizeDropByType.computeIfAbsent(type){java.util.concurrent.atomic.AtomicLong(0)}.incrementAndGet();throw IllegalStateException("WIRE_OVERSIZE_CONTROL_FRAME_${b.size}")}\n    if(b.size>MAX_DATAGRAM_BYTES){if(type in listOf("RANGE_FRAME","CONTROL_FRAME","GEOMETRY_FRAME","GEOMETRY_POSITION_FRAME"))requiredFrameOversizeCount.incrementAndGet();oversizeBlockCount.incrementAndGet();oversizeDropByType.computeIfAbsent(type){java.util.concurrent.atomic.AtomicLong(0)}.incrementAndGet();throw IllegalStateException("WIRE_OVERSIZE_${type}_${b.size}")}','MTU')
s=s.replace('JSONArray(missing.take(64))','JSONArray(missing.take(ARTIFACT_WINDOW_CHUNKS))')
s=rep(s,'        if(a.ackPeers.size<EXPECTED_REMOTE_ACKS&&now-a.lastFullSendWallMs>=FULL_RETRY_MS){for(i in a.chunks.indices)try{out+=chunkFrame(a,i)}catch(t:Throwable){lastSendError="${t.javaClass.simpleName}:${t.message}"};a.lastFullSendWallMs=now}','        if(a.ackPeers.size<EXPECTED_REMOTE_ACKS&&now-a.lastFullSendWallMs>=a.retryBackoffMs){val end=(a.nextChunkIndex+ARTIFACT_WINDOW_CHUNKS).coerceAtMost(a.chunks.size);for(i in a.nextChunkIndex until end)try{out+=chunkFrame(a,i)}catch(t:Throwable){lastSendError="${t.javaClass.simpleName}:${t.message}"};a.nextChunkIndex=if(end>=a.chunks.size)0 else end;if(a.nextChunkIndex==0)a.retryBackoffMs=(a.retryBackoffMs*2).coerceAtMost(MAX_RETRY_BACKOFF_MS);a.lastFullSendWallMs=now}','artifact window')
old='      "ARTIFACT_NACK"->{artifactNackRx.incrementAndGet();val id=o.optString("artifact_id");val a=outboundArtifact(id)?:return ConsumeResult(null,replies);if(a.sha!=o.optString("artifact_sha256"))return ConsumeResult(null,replies);val miss=o.optJSONArray("missing_chunks")?:JSONArray();for(i in 0 until miss.length()){val idx=miss.optInt(i,-1);if(idx in a.chunks.indices){artifactRetransmitChunks.incrementAndGet();replies+=reply(source,chunkFrame(a,idx,now))}};return ConsumeResult(null,replies)}'
new='      "ARTIFACT_NACK"->{artifactNackRx.incrementAndGet();val id=o.optString("artifact_id");val a=outboundArtifact(id)?:return ConsumeResult(null,replies);if(a.sha!=o.optString("artifact_sha256"))return ConsumeResult(null,replies);val miss=o.optJSONArray("missing_chunks")?:JSONArray();val requested=(0 until miss.length()).map{miss.optInt(it,-1)}.filter{it in a.chunks.indices}.distinct().sorted();val sig=requested.joinToString(",");if(sig==a.lastNackSignature&&now-a.lastNackWallMs<NACK_INTERVAL_MS)return ConsumeResult(null,replies);a.lastNackSignature=sig;a.lastNackWallMs=now;for(idx in requested.take(ARTIFACT_WINDOW_CHUNKS)){artifactRetransmitChunks.incrementAndGet();replies+=reply(source,chunkFrame(a,idx,now))};return ConsumeResult(null,replies)}'
s=rep(s,old,new,'NACK dedup')
s=s.replace('.put("schema","WireTransportTelemetryV10").put("max_datagram_budget_bytes",MAX_DATAGRAM_BYTES).put("range_frame_target_bytes",RANGE_FRAME_TARGET_BYTES).put("chunk_payload_bytes",CHUNK_BYTES)','.put("schema","WireTransportTelemetryV10").put("max_datagram_budget_bytes",MAX_DATAGRAM_BYTES).put("range_frame_target_bytes",RANGE_FRAME_TARGET_BYTES).put("control_frame_target_bytes",CONTROL_FRAME_TARGET_BYTES).put("chunk_payload_bytes",CHUNK_BYTES).put("artifact_window_chunks",ARTIFACT_WINDOW_CHUNKS)')
s=s.replace('.put("max_datagram_bytes_observed",maxDatagramBytesObserved.get()).put("max_datagram_bytes_by_type",mapJson(maxBytesByType)).put("wire_oversize_block_count",oversizeBlockCount.get())','.put("max_datagram_bytes_observed",maxDatagramBytesObserved.get()).put("max_datagram_bytes_by_type",mapJson(maxBytesByType)).put("oversize_drop_by_type",mapJson(oversizeDropByType)).put("wire_oversize_block_count",oversizeBlockCount.get())')
s=s.replace('WireEnvelopeV9 compact range','WireEnvelopeV10 compact range')
# bridge owns scenario only at atomic start
s=s.replace('ValidationRuntime.scenario = scenario\n','')
s=s.replace('ValidationRuntime.start(now,FabricRuntime.peerExpireCount.get(),FabricRuntime.totalRebinds(),FabricRuntime.scanRestartCount.get(),FabricRuntime.txPackets.get(),FabricRuntime.rxPackets.get(),preflight.toString())','ValidationRuntime.start(now,FabricRuntime.peerExpireCount.get(),FabricRuntime.totalRebinds(),FabricRuntime.scanRestartCount.get(),FabricRuntime.txPackets.get(),FabricRuntime.rxPackets.get(),preflight.toString(),scenario)')
wr(x,s)
# geometry identity
s=rd('apps/mobile/src/autogeometry.ts').replace('GeometryPublicationV9','GeometryPublicationV10').replace('COORDINATOR_PUBLICATION_V9','COORDINATOR_PUBLICATION_V10');wr('apps/mobile/src/autogeometry.ts',s)
print('dev20.10 source remediation applied')
