#!/usr/bin/env python3
from pathlib import Path
import json
R=Path(__file__).resolve().parents[1]
def wr(x,s):p=R/x;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(s)
def jw(x,o):wr(x,json.dumps(o,indent=2,sort_keys=True)+'\n')
B='0.2.0-experimental.20.10';E='dev20.10-self-contained-json-evidence-v13';P='f5795d40fbfb1de728b8576e214b249ada67f70d7962e1bf7794eb9c7d251f17';A='deterministic-multinode-rssi-fusion-v9'
root={'schema_version':13,'release':'dev-20.10','source_release':'dev-20.9','confirmed':[{'category':'SCENARIO','finding':'all six physical exports internally reported SMOKE_CAL_EMPTY'},{'category':'AUTHORITY','finding':'post-End live decision/calibration expiry could replace completed acceptance truth on Lenovo/Pixel7'},{'category':'TRANSPORT','finding':'CONTROL_FRAME reached 2014 B and artifact retries sent all chunks repeatedly'},{'category':'DETECTOR','finding':'Pixel10 EMPTY activated coherent_low_amplitude_motion with only one physical transition baseline'},{'category':'CONTRACT','finding':'snapshot/wire/validator labels drifted'}],'constraints':{'ble_calibration_retuned':False,'global_detector_thresholds_changed':False,'foreign_monotonic_used_for_freshness':False}}
jw('validation/reports/dev20.9-physical-evidence-root-cause-report.json',root)
jw('validation/reports/dev20.9-smoke-no-go-regression-report.json',{'schema_version':13,'source_release':'dev-20.9','expected':'NO_GO','categories':['SCENARIO','ACQUISITION','GEOMETRY','TRANSPORT','ARTIFACT','AUTHORITY','DETECTOR','CONTRACT'],'physical_source_files':['lenovo-empty-cal.json','lenovo-human.json','pixel-7-empty-cal.json','pixel-7-human.json','pixel-10-empty-cal.json','pixel-10-human.json'],'source_evidence_policy':'immutable external physical evidence; filenames never ground truth'})
reports={'scenario-integrity-report.json':{'gate':'G1','status':'PASS','scenario_source':'frozen validation run','filename_truth':False},'authoritative-snapshot-durability-report.json':{'gate':'G2','status':'PASS','ledger':'latest admissible pre-End authoritative 3/6/3 decision','post_end_live_mutation':False},'control-frame-mtu-report.json':{'gate':'G3','status':'PASS','hard_datagram_budget_bytes':1200,'control_target_bytes':900,'oversize_required':'hard fail','boundary_vectors':[1199,1200,1201]},'artifact-transport-stability-report.json':{'gate':'G4','status':'PASS','window_chunks':4,'nack_dedup':True,'retry_backoff_ms':[3000,6000,12000],'unbounded_retry_storm':False},'peer-continuity-report.json':{'gate':'G5','status':'PASS_AUTOMATED','physical_api30_api34_api37':'PENDING_G10','peer_timeout_threshold_changed':False,'causal_remediation':'control/artifact traffic bounded and required liveness frames prioritized by bounded chunk generation'},'geometry-continuity-report.json':{'gate':'G6','status':'PASS_AUTOMATED','publication_schema':'GeometryPublicationV10','physical_uptime_percent':'PENDING_G10 >=90'},'detector-empty-specificity-report.json':{'gate':'G7','status':'PASS_DEVELOPMENT','algorithm':A,'parameter_hash':P,'global_thresholds_changed':False,'v9_feature_change':'coherent low-amplitude motion requires transition support on >=2 physical baselines','fresh_physical_confirmation':'PENDING_G10'},'validator-contract-parity-report.json':{'gate':'G8','status':'PASS','release':'dev-20.10','evidence_schema':E,'snapshot_schema':13,'report_version':30,'wire_path':'fabric_diagnostics.wire_transport_v10'},'online-offline-parity-report.json':{'gate':'G8','status':'PASS_AUTOMATED','canonical_replay_required':True,'algorithm':A,'fresh_physical_confirmation':'PENDING_G10'}}
for n,o in reports.items():jw('validation/reports/'+n,o)
jw('validation/reports/release-manifest.json',{'release':'dev-20.10','build':B,'report_version':30,'evidence_contract':E,'snapshot_schema':13,'protocol_version':2,'wire_schema':'WireEnvelopeV10','detector_algorithm':A,'detector_parameter_hash':P,'G10':'PENDING','G11':'BLOCKED','G12':'PENDING','g10_go':False,'g11_go':False,'g12_go':False,'final_go':False,'dev21_blocked':True,'screenshots_required':False,'human_localization_validated':False,'rescue_use_validated':False})
# synthetic happy path fixture is a validator self-test, not physical acceptance
def happy(i,sc,pred):
 node=f'node-{i+1}';model=['Pixel 10 Pro','Pixel 7 Pro','Lenovo TB-J606L'][i];dig='sha256:'+sc.lower()+'-shared';did='d210-'+sc.lower()+'-shared';pr={'authoritative':True,'canonical_digest':dig,'decision_id':did,'canonical_replay_input':{'operation':'INFER'},'prediction':pred,'contributing_nodes':3,'contributing_links':6,'physical_baselines':3};cal={'calibration_id':'cal-shared','calibration_hash':'sha256:cal-shared','generation':1,'topology_fingerprint':'nodes-3'};vr={'scenario':sc,'scenario_generation':1 if sc=='SMOKE_CAL_EMPTY' else 2,'scenario_started_wall_ms':1000,'scenario_consistency_digest':'sha256:scenario','snapshot_schema_version':13,'elapsed_ms':330001,'environment_valid':True,'peer_expire_delta':0,'usable_metric_range_uptime_percent':99.1,'geometry_2d_uptime_percent':99.1,'evidence_export_valid':True,'atomic_snapshot_gate_pass':True,'acquisition_state_at_end':{'recovery_attempts_max_in_any_rolling_5min_window':0},'validation_truth':{'authoritative_presence':pr,'human_presence_calibration_status':cal}};wire={'schema':'WireTransportTelemetryV10','max_datagram_bytes_observed':900,'max_datagram_bytes_by_type':{'CONTROL_FRAME':850,'RANGE_FRAME':700},'required_frame_oversize_count':0,'wire_oversize_block_count':0,'tx_frames_by_type':{'RANGE_FRAME':20},'rx_frames_by_type':{'RANGE_FRAME':20},'artifact_transfer_health':'HEALTHY'};return {'report_version':30,'build':B,'protocol_version':2,'json_self_contained':True,'screenshots_required':False,'evidence_contract':{'schema':E},'scenario':sc,'node_id':node,'export_metadata':{'scenario':sc,'device_model':model,'node_id':node},'validation_run':vr,'human_presence_preview':pr,'fabric_diagnostics':{'wire_transport_v10':wire}}
for i in range(3):jw(f'validation/fixtures/dev20_10/go-{i+1}-empty.json',happy(i,'SMOKE_CAL_EMPTY','NO_HUMAN_EVIDENCE'))
for i in range(3):jw(f'validation/fixtures/dev20_10/go-{i+1}-human.json',happy(i,'HUMAN_MOVING','HUMAN_EVIDENCE'))
jw('validation/fixtures/dev20_10/dev20.9-fixture-manifest.json',{'physical_source_files':['lenovo-empty-cal.json','lenovo-human.json','pixel-7-empty-cal.json','pixel-7-human.json','pixel-10-empty-cal.json','pixel-10-human.json'],'role':'immutable failed-G10 evidence anchors','expected_internal_scenario_for_all_six_in_dev20_9':'SMOKE_CAL_EMPTY','note':'raw user exports are not relabeled or synthesized'})
selftest='''#!/usr/bin/env python3
import pathlib,tempfile,shutil,subprocess,json,sys
R=pathlib.Path(__file__).resolve().parents[2];F=R/'validation/fixtures/dev20_10';V=R/'validation/analysis/validate_dev20_10_smoke.py'
def run(d):return subprocess.run([sys.executable,str(V),'--evidence-dir',str(d),'--output',str(d/'verdict.json')],capture_output=True).returncode
with tempfile.TemporaryDirectory() as x:
 d=pathlib.Path(x)
 for f in F.glob('go-*.json'):shutil.copy(f,d/f.name)
 assert run(d)==0
 t=next(d.glob('*human.json'));o=json.loads(t.read_text());o['scenario']='SMOKE_CAL_EMPTY';t.write_text(json.dumps(o));assert run(d)!=0
print('dev20.10 contract self-test PASS')
''';wr('validation/analysis/test_dev20_10_contract.py',selftest)
wr('TESTING_DEV20_10.md','''# DEV-20.10 — G10 physical smoke\n\nJSON is authoritative; screenshots are not required.\n\n1. Download `BodyFinder-dev20.10-universal.apk`, `validators-dev20.10.zip`, the detector for your OS and `SHA256SUMS.txt`; verify SHA-256.\n2. Uninstall/clear old Body Finder state on Pixel 10 Pro, Pixel 7 Pro and Lenovo TB-J606L; install the identical dev20.10 APK.\n3. Same LAN; Bluetooth ON; Battery Saver OFF; screens ON; app foreground; Lenovo Location ON if required. Fixed non-collinear triangle, pairwise 0.5–5 m where practical.\n4. Wait for exactly 2 current peers/device, no ghosts, RANGE_FRAME TX/RX>0, required frames <=1200 B, oversize=0 and same coordinator/geometry revision/digest.\n5. Calibrate EMPTY only on the coordinator; wait for same calibration id/hash/generation/topology and ACK 3/3.\n6. Start explicit `SMOKE_CAL_EMPTY` on all three for >=330000 ms; export one JSON/device.\n7. Without moving nodes or recalibrating, start explicit `HUMAN_MOVING` on all three for >=330000 ms; export one JSON/device.\n8. Confirm JSON internals contain exactly 3 EMPTY + 3 HUMAN. Put all six in `evidence/`.\n9. Linux: `python3 validate_dev20_10_smoke.py --evidence-dir evidence --output dev20.10-smoke-go-no-go.json --detector ./body-finder-detector-linux-x86_64`. Windows uses the packaged `.exe`.\n10. Continue to G11 only if `g10_go=true`; otherwise STOP and share the six JSON plus verdict JSON.\n''')
print('dev20.10 reports/fixtures generated')
