#!/usr/bin/env python3
from pathlib import Path
import re

ROOT=Path(__file__).resolve().parents[1]

def rw(path,fn):
    p=ROOT/path
    old=p.read_text(encoding='utf-8')
    new=fn(old)
    if new!=old:
        p.write_text(new,encoding='utf-8')
        print('updated',path)
    else:
        print('unchanged',path)

def line_sub(s,pattern,repl,label):
    out,n=re.subn(pattern,repl,s,count=1,flags=re.M)
    if n!=1:
        raise SystemExit(f'{label}: expected exactly one replacement, got {n}')
    return out

cc='apps/mobile/src/campaignControl.ts'
def patch_campaign(s):
    if "type RunStartPrepareWireV2=" not in s:
        anchor="export type RunFreezeCommitV2={schema:'RunFreezeCommitV2';campaign_run_token:string;scenario_digest:string;generation:number;authority_view_digest:string;authority_identity_digest:string;readiness_digest:string;committed_by:string;committed_wall_ms:number};\n"
        if anchor not in s: raise SystemExit('wire insertion anchor missing')
        wire="""export type RunFreezeCommitV2={schema:'RunFreezeCommitV2';campaign_run_token:string;scenario_digest:string;generation:number;authority_view_digest:string;authority_identity_digest:string;readiness_digest:string;committed_by:string;committed_wall_ms:number};
type RunStartPrepareWireV2={v:'R2P';t:string;g:number;n:string;w:number;b:string};
type RunStartReadyWireV2={v:'R2R';t:string;g:number;n:string;b:string};
type RunStartCommitWireV2={v:'R2C';t:string;g:number;b:string;r:string;n:string;w:number};
type RunFreezePrepareWireV3={v:'F3P';t:string;g:number;n:string;w:number;b:string};
type RunFreezeReadyWireV3={v:'F3R';t:string;g:number;n:string;b:string};
type RunFreezeCommitWireV3={v:'F3C';t:string;g:number;b:string;r:string;n:string;w:number};
"""
        s=s.replace(anchor,wire)
    helper_anchor="function calibrationIdentity(cal:any){return{calibration_id:String(cal?.calibration_id??''),calibration_hash:String(cal?.calibration_hash??''),calibration_generation:Number(cal?.calibration_generation??cal?.generation??0),topology_hash:topologyHash(cal)}}\n"
    if "function startPrepareBinding" not in s:
        if helper_anchor not in s: raise SystemExit('helper anchor missing')
        helpers=helper_anchor+"""function startPrepareBinding(p:RunStartPrepareV1){return sha({campaign_run_token:p.campaign_run_token,scenario_digest:p.scenario_digest,generation:p.generation,issued_by:p.issued_by,issued_wall_ms:p.issued_wall_ms,calibration_id:p.calibration_id,calibration_hash:p.calibration_hash,calibration_generation:p.calibration_generation,topology_hash:p.topology_hash,cohort:p.cohort.slice().sort(),authority_view_digest:p.authority_view_digest,coordinator_generation:p.coordinator_generation})}
function freezePrepareBinding(p:RunFreezePrepareV2){return sha({campaign_run_token:p.campaign_run_token,scenario_digest:p.scenario_digest,generation:p.generation,issued_by:p.issued_by,issued_wall_ms:p.issued_wall_ms,authority_view_digest:p.authority_view_digest,candidate:p.candidate})}
export function encodeRunStartPrepareWireV2(p:RunStartPrepareV1):RunStartPrepareWireV2{return{v:'R2P',t:p.campaign_run_token,g:p.generation,n:p.issued_by,w:p.issued_wall_ms,b:startPrepareBinding(p)}}
export function encodeRunStartReadyWireV2(r:RunStartReadyV1,p:RunStartPrepareV1):RunStartReadyWireV2{return{v:'R2R',t:r.campaign_run_token,g:r.generation,n:r.node_id,b:startPrepareBinding(p)}}
export function encodeRunStartCommitWireV2(c:RunStartCommitV1,p:RunStartPrepareV1):RunStartCommitWireV2{return{v:'R2C',t:c.campaign_run_token,g:c.generation,b:startPrepareBinding(p),r:c.readiness_digest,n:c.committed_by,w:c.committed_wall_ms}}
export function encodeRunFreezePrepareWireV3(p:RunFreezePrepareV2):RunFreezePrepareWireV3{return{v:'F3P',t:p.campaign_run_token,g:p.generation,n:p.issued_by,w:p.issued_wall_ms,b:freezePrepareBinding(p)}}
export function encodeRunFreezeReadyWireV3(r:SnapshotReadyV2,p:RunFreezePrepareV2):RunFreezeReadyWireV3{return{v:'F3R',t:r.campaign_run_token,g:r.generation,n:r.node_id,b:freezePrepareBinding(p)}}
export function encodeRunFreezeCommitWireV3(c:RunFreezeCommitV2,p:RunFreezePrepareV2):RunFreezeCommitWireV3{return{v:'F3C',t:c.campaign_run_token,g:c.generation,b:freezePrepareBinding(p),r:c.readiness_digest,n:c.committed_by,w:c.committed_wall_ms}}
function decodeStartPrepare(raw:any,nodes:Advertisement[],coordinatorId:string|null,localId:string|null,cal:any,s:State,a:any):RunStartPrepareV1|null{if(raw?.v!=='R2P'||!a.view||!s.command||!coordinatorId||raw.n!==coordinatorId)return null;const generation=Number(raw.g),issued_wall_ms=Number(raw.w),ci=calibrationIdentity(cal),ids=cohort(nodes).slice().sort();if(!Number.isSafeInteger(generation)||generation<=0||!Number.isFinite(issued_wall_ms)||ids.length!==3||!ci.calibration_id||!ci.calibration_hash||!ci.topology_hash)return null;const token=sha({session_id:session(nodes),scenario_digest:s.command.command_digest,calibration:ci,cohort:a.view.cohort,authority_view_digest:a.view.authority_view_digest,generation,issued_wall_ms});if(raw.t!==token)return null;const p:RunStartPrepareV1={schema:'RunStartPrepareV1',campaign_run_token:token,scenario_digest:s.command.command_digest,generation,issued_by:coordinatorId,issued_wall_ms,...ci,cohort:ids,authority_view_digest:a.view.authority_view_digest,coordinator_generation:a.view.coordinator_generation};return raw.b===startPrepareBinding(p)?p:null}
function decodeStartReady(raw:any,p:RunStartPrepareV1,ids:string[]):RunStartReadyV1|null{if(raw?.v!=='R2R'||raw.t!==p.campaign_run_token||Number(raw.g)!==p.generation||!ids.includes(String(raw.n))||raw.b!==startPrepareBinding(p))return null;const ci={calibration_id:p.calibration_id,calibration_hash:p.calibration_hash,calibration_generation:p.calibration_generation,topology_hash:p.topology_hash},authority_identity_digest=sha({campaign_run_token:p.campaign_run_token,scenario_digest:p.scenario_digest,authority_view_digest:p.authority_view_digest,...ci});return{schema:'RunStartReadyV1',node_id:String(raw.n),campaign_run_token:p.campaign_run_token,generation:p.generation,scenario_digest:p.scenario_digest,...ci,authority_view_digest:p.authority_view_digest,coordinator_generation:p.coordinator_generation,authority_identity_digest}}
function decodeStartCommit(raw:any,p:RunStartPrepareV1):RunStartCommitV1|null{if(raw?.v!=='R2C'||raw.t!==p.campaign_run_token||Number(raw.g)!==p.generation||raw.b!==startPrepareBinding(p)||typeof raw.r!=='string'||typeof raw.n!=='string'||!Number.isFinite(Number(raw.w)))return null;return{schema:'RunStartCommitV1',campaign_run_token:p.campaign_run_token,generation:p.generation,scenario_digest:p.scenario_digest,authority_view_digest:p.authority_view_digest,coordinator_generation:p.coordinator_generation,readiness_digest:String(raw.r),committed_by:String(raw.n),committed_wall_ms:Number(raw.w)}}
function decodeFreezePrepare(raw:any,nodes:Advertisement[],coordinatorId:string|null,localId:string|null,authority:any,cal:any,s:State,a:any):RunFreezePrepareV2|null{if(raw?.v!=='F3P'||!a.view||!s.startCommit||!coordinatorId||raw.n!==coordinatorId||raw.t!==s.startCommit.campaign_run_token)return null;const candidate=candidateFrom(authority,cal),generation=Number(raw.g),issued_wall_ms=Number(raw.w);if(!candidate||!Number.isSafeInteger(generation)||generation<=0||!Number.isFinite(issued_wall_ms))return null;const p:RunFreezePrepareV2={schema:'RunFreezePrepareV2',campaign_run_token:s.startCommit.campaign_run_token,scenario_digest:s.startCommit.scenario_digest,generation,issued_by:coordinatorId,issued_wall_ms,authority_view_digest:a.view.authority_view_digest,candidate};return raw.b===freezePrepareBinding(p)?p:null}
function decodeFreezeReady(raw:any,p:RunFreezePrepareV2,ids:string[]):SnapshotReadyV2|null{if(raw?.v!=='F3R'||raw.t!==p.campaign_run_token||Number(raw.g)!==p.generation||!ids.includes(String(raw.n))||raw.b!==freezePrepareBinding(p))return null;const c=p.candidate;return{schema:'SnapshotReadyV2',node_id:String(raw.n),campaign_run_token:p.campaign_run_token,scenario_digest:p.scenario_digest,generation:p.generation,authority_view_digest:p.authority_view_digest,authority_identity_digest:c.authority_identity_digest,replay_hash:c.replay_hash,replay_artifact_id:c.replay_artifact_id,calibration_id:c.calibration_id,calibration_hash:c.calibration_hash,calibration_generation:c.calibration_generation,topology_hash:c.topology_hash}}
function decodeFreezeCommit(raw:any,p:RunFreezePrepareV2):RunFreezeCommitV2|null{if(raw?.v!=='F3C'||raw.t!==p.campaign_run_token||Number(raw.g)!==p.generation||raw.b!==freezePrepareBinding(p)||typeof raw.r!=='string'||typeof raw.n!=='string'||!Number.isFinite(Number(raw.w)))return null;return{schema:'RunFreezeCommitV2',campaign_run_token:p.campaign_run_token,scenario_digest:p.scenario_digest,generation:p.generation,authority_view_digest:p.authority_view_digest,authority_identity_digest:p.candidate.authority_identity_digest,readiness_digest:String(raw.r),committed_by:String(raw.n),committed_wall_ms:Number(raw.w)}}
"""
        s=s.replace(helper_anchor,helpers)

    s=line_sub(s,r"^function syncStart\([^\n]*$", "function syncStart(nodes:Advertisement[],coordinatorId:string|null,localId:string|null,cal:any){const s=st(nodes,localId),a=bind(nodes,localId,s);if(!a.view||!coordinatorId||coordinatorId===localId)return;const cp=coordinatorNode(nodes,coordinatorId)?.control_plane as any,p=decodeStartPrepare(cp?.run_start_prepare_v1,nodes,coordinatorId,localId,cal,s,a);if(p&&(!s.startPrepare||p.generation>=s.startPrepare.generation))s.startPrepare=p;const c=s.startPrepare?decodeStartCommit(cp?.run_start_commit_v1,s.startPrepare):null;if(c&&c.committed_by===coordinatorId)s.startCommit=c}", 'syncStart')
    s=line_sub(s,r"^export function getRunStartBarrierStatus\([^\n]*$", "export function getRunStartBarrierStatus(nodes:Advertisement[],coordinatorId:string|null,localId:string|null,cal:any){syncScenario(nodes,coordinatorId,localId);syncStart(nodes,coordinatorId,localId,cal);const s=st(nodes,localId),a=bind(nodes,localId,s),ids=cohort(nodes),local=localStartReady(nodes,localId,cal),ready:RunStartReadyV1[]=[];for(const id of ids){if(id===localId&&local)ready.push(local);else if(s.startPrepare){const raw=(nodes.find(n=>n.node_id===id)?.control_plane as any)?.run_start_ready_v1,x=decodeStartReady(raw,s.startPrepare,ids);if(x&&x.node_id===id)ready.push(x)}}const parity=ready.length===3&&new Set(ready.map(r=>r.authority_identity_digest)).size===1&&Boolean(a.view&&ready.every(r=>r.authority_view_digest===a.view!.authority_view_digest));if(coordinatorId===localId&&a.view&&a.consensus&&s.startPrepare&&parity&&!s.startCommit)s.startCommit={schema:'RunStartCommitV1',campaign_run_token:s.startPrepare.campaign_run_token,generation:s.startPrepare.generation,scenario_digest:s.startPrepare.scenario_digest,authority_view_digest:a.view.authority_view_digest,coordinator_generation:a.view.coordinator_generation,readiness_digest:sha(ready.slice().sort((x,y)=>x.node_id.localeCompare(y.node_id))),committed_by:localId!,committed_wall_ms:Date.now()};return{schema:'RunStartBarrierV1',wire_schema:'RunStartWireV2',authority_view_digest:a.view?.authority_view_digest??null,authority_ack_count:a.ack_count,prepare:s.startPrepare,local_ready:local,ready_count:ready.length,ready_nodes:ready.map(r=>r.node_id).sort(),ready_parity:parity,commit:s.startCommit,committed:Boolean(s.startCommit&&s.startPrepare&&s.startCommit.campaign_run_token===s.startPrepare.campaign_run_token)}}", 'getRunStartBarrierStatus')
    s=line_sub(s,r"^function syncFreeze\([^\n]*$", "function syncFreeze(nodes:Advertisement[],coordinatorId:string|null,localId:string|null,authority:any,cal:any){const s=st(nodes,localId),a=bind(nodes,localId,s);if(!a.view||!coordinatorId||coordinatorId===localId)return;const cp=coordinatorNode(nodes,coordinatorId)?.control_plane as any,p=decodeFreezePrepare(cp?.run_freeze_prepare_v2,nodes,coordinatorId,localId,authority,cal,s,a);if(p&&(!s.freezePrepare||p.generation>=s.freezePrepare.generation))s.freezePrepare=p;const c=s.freezePrepare?decodeFreezeCommit(cp?.run_freeze_commit_v2,s.freezePrepare):null;if(c&&c.committed_by===coordinatorId)s.freezeCommit=c}", 'syncFreeze')
    s=line_sub(s,r"^export function requestRunFreeze\([^\n]*$", "export function requestRunFreeze(nodes:Advertisement[],coordinatorId:string|null,localId:string|null,authority:any,cal:any){syncScenario(nodes,coordinatorId,localId);syncStart(nodes,coordinatorId,localId,cal);const s=st(nodes,localId),a=bind(nodes,localId,s);if(!localId||coordinatorId!==localId||!a.view||!a.consensus)throw new Error('RUN_FREEZE_AUTHORITY_REQUIRED');if(!s.startCommit||s.startCommit.authority_view_digest!==a.view.authority_view_digest)throw new Error('RUN_FREEZE_START_COMMIT_REQUIRED');const candidate=candidateFrom(authority,cal);if(!candidate)throw new Error('RUN_FREEZE_FINAL_DECISION_CANDIDATE_NOT_ADMISSIBLE');if(candidate.calibration_id!==s.startPrepare?.calibration_id||candidate.calibration_hash!==s.startPrepare?.calibration_hash||candidate.calibration_generation!==s.startPrepare?.calibration_generation)throw new Error('RUN_FREEZE_CALIBRATION_MISMATCH');const generation=(s.freezePrepare?.generation??0)+1;s.freezePrepare={schema:'RunFreezePrepareV2',campaign_run_token:s.startCommit.campaign_run_token,scenario_digest:s.startCommit.scenario_digest,generation,issued_by:localId,issued_wall_ms:Date.now(),authority_view_digest:a.view.authority_view_digest,candidate};s.freezeCommit=null;return s.freezePrepare}", 'requestRunFreeze')
    s=line_sub(s,r"^export function getFreezeBarrierStatus\([^\n]*$", "export function getFreezeBarrierStatus(nodes:Advertisement[],coordinatorId:string|null,localId:string|null,authority:any,cal:any){syncScenario(nodes,coordinatorId,localId);syncStart(nodes,coordinatorId,localId,cal);syncFreeze(nodes,coordinatorId,localId,authority,cal);const s=st(nodes,localId),a=bind(nodes,localId,s),ids=cohort(nodes),local=localFreezeReady(nodes,coordinatorId,localId,cal),ready:SnapshotReadyV2[]=[];for(const id of ids){if(id===localId&&local)ready.push(local);else if(s.freezePrepare){const cp=nodes.find(n=>n.node_id===id)?.control_plane as any,raw=cp?.run_freeze_ready_v2??cp?.snapshot_ready_v2,x=decodeFreezeReady(raw,s.freezePrepare,ids);if(x&&x.node_id===id)ready.push(x)}}const parity=ready.length===3&&s.freezePrepare!=null&&a.view!=null&&ready.every(r=>r.authority_view_digest===a.view!.authority_view_digest&&r.authority_identity_digest===s.freezePrepare!.candidate.authority_identity_digest&&r.replay_hash===s.freezePrepare!.candidate.replay_hash);if(coordinatorId===localId&&s.freezePrepare&&a.view&&parity&&!s.freezeCommit)s.freezeCommit={schema:'RunFreezeCommitV2',campaign_run_token:s.freezePrepare.campaign_run_token,scenario_digest:s.freezePrepare.scenario_digest,generation:s.freezePrepare.generation,authority_view_digest:a.view.authority_view_digest,authority_identity_digest:s.freezePrepare.candidate.authority_identity_digest,readiness_digest:sha(ready.slice().sort((x,y)=>x.node_id.localeCompare(y.node_id))),committed_by:localId!,committed_wall_ms:Date.now()};return{schema:'SnapshotFreezeV2',wire_schema:'RunFreezeWireV3',authority_view_digest:a.view?.authority_view_digest??null,prepare:s.freezePrepare,local_ready:local,ready_count:ready.length,ready_nodes:ready.map(r=>r.node_id).sort(),ready_parity:parity,commit:s.freezeCommit,committed:Boolean(s.freezeCommit&&s.freezePrepare&&s.freezeCommit.campaign_run_token===s.freezePrepare.campaign_run_token)}}", 'getFreezeBarrierStatus')
    s=line_sub(s,r"^export function getCampaignControlPublication\([^\n]*$", "export function getCampaignControlPublication(nodes:Advertisement[],coordinatorId:string|null,localId:string|null,authority:any,cal:any){const sstat=getScenarioCommandStatus(nodes,coordinatorId,localId),start=getRunStartBarrierStatus(nodes,coordinatorId,localId,cal),freeze=getFreezeBarrierStatus(nodes,coordinatorId,localId,authority,cal),s=st(nodes,localId),a=bind(nodes,localId,s),artifacts:any[]=[];if(coordinatorId===localId&&s.freezePrepare){const d=authority?.decision??authority?.authoritative_presence??authority;if(d?.canonical_replay_input&&s.freezePrepare.candidate?.replay_artifact_id)artifacts.push({artifact_id:s.freezePrepare.candidate.replay_artifact_id,artifact_type:'DECISION_FINAL_REPLAY_V1',generation:s.freezePrepare.generation,priority:'DECISION_FINAL',supersedes_artifact_id:null,payload:d.canonical_replay_input})}const c=sstat.command;return{scenario_command_v1:coordinatorId===localId?c:null,scenario_ack_v1:c&&localId&&a.view?{schema:'ScenarioAckV1',node_id:localId,scenario_generation:c.scenario_generation,command_digest:c.command_digest,authority_view_digest:a.view.authority_view_digest}:null,run_start_prepare_v1:coordinatorId===localId&&start.prepare?encodeRunStartPrepareWireV2(start.prepare):null,run_start_ready_v1:start.local_ready&&start.prepare?encodeRunStartReadyWireV2(start.local_ready,start.prepare):null,run_start_commit_v1:coordinatorId===localId&&start.commit&&start.prepare?encodeRunStartCommitWireV2(start.commit,start.prepare):null,run_freeze_prepare_v2:coordinatorId===localId&&freeze.prepare?encodeRunFreezePrepareWireV3(freeze.prepare):null,run_freeze_ready_v2:freeze.local_ready&&freeze.prepare?encodeRunFreezeReadyWireV3(freeze.local_ready,freeze.prepare):null,run_freeze_commit_v2:coordinatorId===localId&&freeze.commit&&freeze.prepare?encodeRunFreezeCommitWireV3(freeze.commit,freeze.prepare):null,artifact_payloads_v1:artifacts}}", 'getCampaignControlPublication')
    if 'snapshot_ready_v2:freeze.local_ready' in s: raise SystemExit('legacy snapshot_ready_v2 outbound publication remains')
    return s
rw(cc,patch_campaign)

# Coherent dev20.17 identity.
versioned=['apps/mobile/src/version.ts','apps/mobile/app.json','apps/mobile/package.json','apps/mobile/package-lock.json','apps/android-legacy/app/build.gradle','apps/mobile/App.tsx']
for path in versioned:
    p=ROOT/path
    if not p.exists(): continue
    def bump(s,path=path):
        s=s.replace('0.2.0-experimental.20.16','0.2.0-experimental.20.17')
        s=s.replace('experimental.20.16','experimental.20.17')
        s=s.replace('dev-20.16','dev-20.17').replace('dev20.16','dev20.17')
        if path.endswith('version.ts'):
            s=s.replace('reportVersion: 36','reportVersion: 37').replace('versionCode: 36','versionCode: 37')
        return s
    rw(path,bump)

print('DEV20_17_IMPLEMENTATION_APPLIED')
